CREATE TABLE `schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`startTime` timestamp NOT NULL,
	`endTime` timestamp,
	`isAllDay` boolean NOT NULL DEFAULT false,
	`category` enum('delivery','meeting','live','other') NOT NULL DEFAULT 'other',
	`liverId` int,
	`liverName` varchar(255),
	`brandId` int,
	`lineGroupId` varchar(64),
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurringPattern` enum('daily','weekly','monthly','yearly'),
	`recurringEndDate` timestamp,
	`parentScheduleId` int,
	`status` enum('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled',
	`notes` text,
	`createdBy` int,
	`createdByLineUserId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `schedules_id` PRIMARY KEY(`id`)
);
