CREATE TABLE `ad_proposal_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandId` int NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`proposalContent` text NOT NULL,
	`totalGmv` bigint DEFAULT 0,
	`totalImpressions` bigint DEFAULT 0,
	`adValue` bigint DEFAULT 0,
	`totalValue` bigint DEFAULT 0,
	`totalAdCost` bigint DEFAULT 0,
	`avgRoas` decimal(10,2) DEFAULT '0',
	`totalLivestreams` int DEFAULT 0,
	`avgSalesPerLive` bigint DEFAULT 0,
	`avgDuration` int DEFAULT 0,
	`productsCount` int DEFAULT 0,
	`activeContractsCount` int DEFAULT 0,
	`topProducts` json,
	`status` enum('draft','submitted','approved','rejected') NOT NULL DEFAULT 'draft',
	`createdBy` int NOT NULL,
	`createdByName` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_proposal_history_id` PRIMARY KEY(`id`)
);
