CREATE TABLE `ad_alert_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandId` int NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`aiAnalysis` text NOT NULL,
	`totalGmv` bigint DEFAULT 0,
	`totalImpressions` bigint DEFAULT 0,
	`avgConversionRate` decimal(10,4) DEFAULT '0',
	`totalLivestreams` int DEFAULT 0,
	`avgGmvPerLive` bigint DEFAULT 0,
	`performanceScore` int DEFAULT 0,
	`missedImpressions` bigint DEFAULT 0,
	`missedGmv` bigint DEFAULT 0,
	`scenarios` json,
	`allocationLiveRatio` decimal(5,2) DEFAULT '0.5',
	`allocationClipRatio` decimal(5,2) DEFAULT '0.5',
	`allocationReason` text,
	`urgencyLevel` enum('high','medium','low') NOT NULL DEFAULT 'medium',
	`createdBy` int NOT NULL,
	`createdByName` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_alert_history_id` PRIMARY KEY(`id`)
);
