CREATE TABLE `ad_investment_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandId` int NOT NULL,
	`investmentDate` timestamp NOT NULL,
	`adType` enum('live','clip','mixed') NOT NULL DEFAULT 'mixed',
	`totalBudget` bigint NOT NULL,
	`liveBudget` bigint DEFAULT 0,
	`clipBudget` bigint DEFAULT 0,
	`actualGmv` bigint DEFAULT 0,
	`actualImpressions` bigint DEFAULT 0,
	`actualClicks` bigint DEFAULT 0,
	`actualConversions` int DEFAULT 0,
	`actualRoas` decimal(10,4) DEFAULT '0',
	`cpm` decimal(10,2) DEFAULT '0',
	`cpc` decimal(10,2) DEFAULT '0',
	`conversionRate` decimal(10,4) DEFAULT '0',
	`predictedGmv` bigint DEFAULT 0,
	`predictedRoas` decimal(10,4) DEFAULT '0',
	`predictionAccuracy` decimal(10,4) DEFAULT '0',
	`campaignName` varchar(255),
	`notes` text,
	`livestreamId` int,
	`createdBy` int NOT NULL,
	`createdByName` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_investment_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `brand_ad_performance_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandId` int NOT NULL,
	`avgRoas` decimal(10,4) DEFAULT '0',
	`avgCpm` decimal(10,2) DEFAULT '0',
	`avgCpc` decimal(10,2) DEFAULT '0',
	`avgConversionRate` decimal(10,4) DEFAULT '0',
	`liveAdAvgRoas` decimal(10,4) DEFAULT '0',
	`clipAdAvgRoas` decimal(10,4) DEFAULT '0',
	`optimalLiveRatio` decimal(5,2) DEFAULT '0.5',
	`optimalClipRatio` decimal(5,2) DEFAULT '0.5',
	`avgPredictionAccuracy` decimal(10,4) DEFAULT '0',
	`totalRecords` int DEFAULT 0,
	`lastCalculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `brand_ad_performance_stats_id` PRIMARY KEY(`id`),
	CONSTRAINT `brand_ad_performance_stats_brandId_unique` UNIQUE(`brandId`)
);
