CREATE TABLE `screenshot_analysis_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`liverId` int,
	`livestreamId` int,
	`imageHash` varchar(128) NOT NULL,
	`imageUrl` text,
	`imageKey` varchar(512),
	`salesAmount` bigint,
	`viewerCount` int,
	`peakViewerCount` int,
	`productClicks` int,
	`orderCount` int,
	`durationMinutes` int,
	`startDateTime` varchar(20),
	`endDateTime` varchar(20),
	`impressions` int,
	`liveCtr` varchar(20),
	`orderRate` varchar(20),
	`productSales` int,
	`confidence` enum('high','medium','low') DEFAULT 'medium',
	`rawResponse` json,
	`analysisVersion` varchar(20) DEFAULT '1.0',
	`analyzedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `screenshot_analysis_history_id` PRIMARY KEY(`id`)
);
