CREATE TABLE IF NOT EXISTS `finance_import_documents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `module` ENUM('bank_statement','payroll','tiktok_orders','tiktok_payment','tap','cap_creator','cap_product') NOT NULL,
  `entity` ENUM('japan','china','all') DEFAULT NULL,
  `brandId` INT DEFAULT NULL,
  `reportMonth` VARCHAR(7) DEFAULT NULL,
  `sourceFileName` VARCHAR(500) NOT NULL,
  `sourceFileSha256` CHAR(64) NOT NULL,
  `sourceFileSize` BIGINT UNSIGNED NOT NULL,
  `sourceMimeType` VARCHAR(255) NOT NULL,
  `sourceStorageKey` VARCHAR(1000) DEFAULT NULL,
  `recordCount` INT NOT NULL DEFAULT 0,
  `importedCount` INT NOT NULL DEFAULT 0,
  `skippedCount` INT NOT NULL DEFAULT 0,
  `errorCount` INT NOT NULL DEFAULT 0,
  `status` ENUM('processing','completed','failed') NOT NULL DEFAULT 'processing',
  `errorMessage` TEXT DEFAULT NULL,
  `details` JSON DEFAULT NULL,
  `relatedImportId` BIGINT DEFAULT NULL,
  `createdBy` INT DEFAULT NULL,
  `createdByName` VARCHAR(255) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_finance_import_created` (`createdAt`),
  KEY `idx_finance_import_module_created` (`module`, `createdAt`),
  KEY `idx_finance_import_context` (`entity`, `brandId`, `reportMonth`),
  KEY `idx_finance_import_hash` (`sourceFileSha256`)
);
