CREATE TABLE IF NOT EXISTS `cashflow_internal_transfers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `transferKey` VARCHAR(64) NOT NULL,
  `sourceCashflowId` INT NOT NULL,
  `destinationCashflowId` INT NOT NULL,
  `activeSourceCashflowId` INT DEFAULT NULL,
  `activeDestinationCashflowId` INT DEFAULT NULL,
  `status` ENUM('linked','unlinked') NOT NULL DEFAULT 'linked',
  `sourceAmount` DECIMAL(15,2) NOT NULL,
  `sourceTransferAmount` DECIMAL(15,2) NOT NULL,
  `sourceFeeAmount` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `sourceCurrency` ENUM('JPY','CNY') NOT NULL,
  `destinationAmount` DECIMAL(15,2) NOT NULL,
  `destinationCurrency` ENUM('JPY','CNY') NOT NULL,
  `actualJpyPerCny` DECIMAL(18,8) DEFAULT NULL,
  `note` VARCHAR(500) DEFAULT NULL,
  `createdBy` INT DEFAULT NULL,
  `unlinkedBy` INT DEFAULT NULL,
  `unlinkedAt` TIMESTAMP NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cashflow_transfer_key` (`transferKey`),
  UNIQUE KEY `uq_cashflow_transfer_active_source` (`activeSourceCashflowId`),
  UNIQUE KEY `uq_cashflow_transfer_active_destination` (`activeDestinationCashflowId`),
  KEY `idx_cashflow_transfer_source` (`sourceCashflowId`),
  KEY `idx_cashflow_transfer_destination` (`destinationCashflowId`),
  KEY `idx_cashflow_transfer_created` (`createdAt`)
);
