CREATE TABLE IF NOT EXISTS `brand_day_events` (
  `id` int AUTO_INCREMENT NOT NULL,
  `brand_id` int NULL,
  `slug` varchar(120) NOT NULL,
  `title` varchar(255) NOT NULL,
  `short_name` varchar(120) NOT NULL,
  `timezone` varchar(64) NOT NULL DEFAULT 'Asia/Tokyo',
  `event_start_at` timestamp NOT NULL,
  `event_end_at` timestamp NOT NULL,
  `registration_open_at` timestamp NULL,
  `registration_close_at` timestamp NULL,
  `minimum_stream_minutes` int NOT NULL DEFAULT 60,
  `status` enum('draft','registration','active','closed','archived') NOT NULL DEFAULT 'draft',
  `logo_key` varchar(500) NULL,
  `logo_url` text NULL,
  `theme_json` json NULL,
  `rules_json` json NULL,
  `source_system` varchar(80) NULL,
  `source_event_id` varchar(120) NULL,
  `legacy_base_url` varchar(500) NULL,
  `created_by` int NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_events_slug_unique` (`slug`),
  UNIQUE KEY `bd_events_source_unique` (`source_system`,`source_event_id`),
  KEY `bd_events_brand_idx` (`brand_id`),
  KEY `bd_events_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_entries` (
  `id` int AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `registration_name` varchar(120) NOT NULL,
  `tiktok_id` varchar(120) NOT NULL,
  `tiktok_name` varchar(160) NOT NULL,
  `line_id` varchar(120) NOT NULL,
  `phone` varchar(40) NOT NULL,
  `email` varchar(320) NOT NULL,
  `dashboard_password_hash` varchar(255) NOT NULL,
  `status` enum('pending','approved','suspended') NOT NULL DEFAULT 'pending',
  `source_system` varchar(80) NULL,
  `source_entry_id` int NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_entries_event_tiktok_unique` (`event_id`,`tiktok_id`),
  UNIQUE KEY `bd_entries_event_email_unique` (`event_id`,`email`),
  UNIQUE KEY `bd_entries_source_unique` (`event_id`,`source_system`,`source_entry_id`),
  KEY `bd_entries_event_status_idx` (`event_id`,`status`),
  CONSTRAINT `bd_entries_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_creator_accounts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `entry_id` int NULL,
  `tiktok_id` varchar(120) NOT NULL,
  `tiktok_name` varchar(160) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `status` enum('active','suspended') NOT NULL DEFAULT 'active',
  `source_system` varchar(80) NULL,
  `source_account_id` int NULL,
  `last_signed_in_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_accounts_event_tiktok_unique` (`event_id`,`tiktok_id`),
  UNIQUE KEY `bd_accounts_event_entry_unique` (`event_id`,`entry_id`),
  UNIQUE KEY `bd_accounts_source_unique` (`event_id`,`source_system`,`source_account_id`),
  KEY `bd_accounts_event_status_idx` (`event_id`,`status`),
  CONSTRAINT `bd_accounts_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bd_accounts_entry_fk` FOREIGN KEY (`entry_id`) REFERENCES `brand_day_entries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_creator_sessions` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `creator_account_id` int NOT NULL,
  `token_hash` varchar(64) NOT NULL,
  `expires_at` timestamp NOT NULL,
  `revoked_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_sessions_token_unique` (`token_hash`),
  KEY `bd_sessions_account_idx` (`creator_account_id`,`expires_at`),
  CONSTRAINT `bd_sessions_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bd_sessions_account_fk` FOREIGN KEY (`creator_account_id`) REFERENCES `brand_day_creator_accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_performances` (
  `id` int AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `creator_account_id` int NOT NULL,
  `day_number` int NOT NULL,
  `session_number` int NOT NULL DEFAULT 1,
  `stream_date` timestamp NOT NULL,
  `started_at` timestamp NULL,
  `ended_at` timestamp NULL,
  `stream_minutes` int NOT NULL DEFAULT 0,
  `total_gmv` bigint NOT NULL DEFAULT 0,
  `brand_gmv` bigint NOT NULL DEFAULT 0,
  `screenshot_key` varchar(500) NULL,
  `screenshot_url` text NULL,
  `screenshot_hash` varchar(64) NULL,
  `screenshot_mime_type` varchar(100) NULL,
  `ai_status` enum('idle','processing','completed','failed') NOT NULL DEFAULT 'idle',
  `ai_model` varchar(120) NULL,
  `ai_report` text NULL,
  `status` enum('draft','submitted','reviewed','reflected') NOT NULL DEFAULT 'draft',
  `review_decision` enum('pending','approved','force_approved','rejected') NULL,
  `review_reason` text NULL,
  `force_include_outside_window` tinyint(1) NOT NULL DEFAULT 0,
  `reviewed_by` int NULL,
  `reviewed_at` timestamp NULL,
  `source_system` varchar(80) NULL,
  `source_performance_id` int NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_perf_event_creator_day_session_unique` (`event_id`,`creator_account_id`,`day_number`,`session_number`),
  UNIQUE KEY `bd_perf_event_creator_hash_unique` (`event_id`,`creator_account_id`,`screenshot_hash`),
  UNIQUE KEY `bd_perf_source_unique` (`event_id`,`source_system`,`source_performance_id`),
  KEY `bd_perf_event_status_idx` (`event_id`,`status`),
  KEY `bd_perf_review_idx` (`event_id`,`review_decision`),
  CONSTRAINT `bd_perf_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bd_perf_account_fk` FOREIGN KEY (`creator_account_id`) REFERENCES `brand_day_creator_accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_performance_products` (
  `id` int AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `performance_id` int NOT NULL,
  `product_name` varchar(500) NOT NULL,
  `gmv` bigint NOT NULL DEFAULT 0,
  `brand_gmv` bigint NOT NULL DEFAULT 0,
  `is_brand_product` tinyint(1) NOT NULL DEFAULT 0,
  `selected` tinyint(1) NOT NULL DEFAULT 1,
  `confidence_basis_points` int NOT NULL DEFAULT 0,
  `source_system` varchar(80) NULL,
  `source_product_id` int NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_products_source_unique` (`event_id`,`source_system`,`source_product_id`),
  KEY `bd_products_performance_idx` (`performance_id`),
  CONSTRAINT `bd_products_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bd_products_performance_fk` FOREIGN KEY (`performance_id`) REFERENCES `brand_day_performances` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_audit_logs` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `event_id` int NOT NULL,
  `creator_account_id` int NULL,
  `actor_user_id` int NULL,
  `actor_name` varchar(255) NULL,
  `actor_type` enum('creator','staff','admin','system','migration') NOT NULL DEFAULT 'system',
  `action` varchar(120) NOT NULL,
  `entity_type` varchar(80) NOT NULL,
  `entity_id` int NULL,
  `detail` json NULL,
  `source_system` varchar(80) NULL,
  `source_audit_id` int NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_audit_source_unique` (`event_id`,`source_system`,`source_audit_id`),
  KEY `bd_audit_entity_idx` (`event_id`,`entity_type`,`entity_id`),
  KEY `bd_audit_created_idx` (`event_id`,`created_at`),
  CONSTRAINT `bd_audit_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `brand_day_migration_runs` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `source_system` varchar(80) NOT NULL,
  `migration_key` varchar(160) NOT NULL,
  `event_id` int NULL,
  `status` enum('preview','running','completed','failed','rolled_back') NOT NULL DEFAULT 'preview',
  `source_counts` json NULL,
  `target_counts` json NULL,
  `manifest_sha256` varchar(64) NOT NULL,
  `error_summary` text NULL,
  `started_by` int NULL,
  `started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` timestamp NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bd_migration_unique` (`source_system`,`migration_key`),
  KEY `bd_migration_status_idx` (`status`),
  CONSTRAINT `bd_migration_event_fk` FOREIGN KEY (`event_id`) REFERENCES `brand_day_events` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
