CREATE TABLE IF NOT EXISTS `festival_bulk_email_campaigns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` ENUM('queued','processing','completed','partial','cancelled') NOT NULL DEFAULT 'queued',
  `event_year` VARCHAR(10) NOT NULL DEFAULT 'all',
  `audience_types` JSON NOT NULL,
  `selection_json` JSON NOT NULL,
  `subject_template` VARCHAR(500) NOT NULL,
  `body_template` TEXT NOT NULL,
  `recipient_count` INT NOT NULL DEFAULT 0,
  `sent_count` INT NOT NULL DEFAULT 0,
  `failed_count` INT NOT NULL DEFAULT 0,
  `created_by_account_id` INT NOT NULL,
  `created_by_email` VARCHAR(320) NOT NULL,
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_lcf_bulk_campaign_status_created` (`status`, `created_at`),
  INDEX `idx_lcf_bulk_campaign_creator_created` (`created_by_account_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `festival_bulk_email_recipients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `campaign_id` BIGINT NOT NULL,
  `application_type` ENUM('company','liver','general','sponsor') NOT NULL,
  `application_id` INT NOT NULL,
  `event_year` VARCHAR(10) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) NULL,
  `subject` VARCHAR(500) NOT NULL,
  `body` TEXT NOT NULL,
  `status` ENUM('pending','sending','sent','failed','cancelled') NOT NULL DEFAULT 'pending',
  `attempt_count` INT NOT NULL DEFAULT 0,
  `message_id` VARCHAR(255) NULL,
  `error_code` VARCHAR(100) NULL,
  `sent_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_lcf_bulk_recipient_campaign_email` (`campaign_id`, `email`),
  INDEX `idx_lcf_bulk_recipient_campaign_status` (`campaign_id`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
