CREATE TABLE IF NOT EXISTS `line_ai_manager_settings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `lineUserId` varchar(64) NOT NULL,
  `liverId` int NOT NULL,
  `replyEnabled` boolean NOT NULL DEFAULT true,
  `proactiveEnabled` boolean NOT NULL DEFAULT false,
  `tiktokAnalysisEnabled` boolean NOT NULL DEFAULT true,
  `inactivityDays` int NOT NULL DEFAULT 3,
  `maxProactivePerCycle` int NOT NULL DEFAULT 2,
  `tone` enum('warm','professional','energetic') NOT NULL DEFAULT 'warm',
  `lastInboundAt` timestamp NULL,
  `lastReplyAt` timestamp NULL,
  `lastProactiveAt` timestamp NULL,
  `consecutiveProactiveCount` int NOT NULL DEFAULT 0,
  `lastIntent` varchar(100),
  `nextAction` text,
  `lastResponsePreview` text,
  `tiktokInsight` json,
  `tiktokInsightUpdatedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `line_ai_manager_settings_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_line_ai_manager_user` UNIQUE(`lineUserId`),
  INDEX `idx_line_ai_manager_liver` (`liverId`),
  INDEX `idx_line_ai_manager_proactive` (`proactiveEnabled`, `lastInboundAt`, `lastProactiveAt`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `line_ai_manager_events` (
  `id` int AUTO_INCREMENT NOT NULL,
  `eventKey` varchar(160) NOT NULL,
  `sourceMessageId` varchar(64),
  `lineUserId` varchar(64) NOT NULL,
  `liverId` int NOT NULL,
  `triggerType` enum('reply','inactivity_follow_up') NOT NULL,
  `status` enum('queued','processing','ready','sending','sent','failed','skipped','unknown') NOT NULL DEFAULT 'queued',
  `model` varchar(100),
  `attemptCount` int NOT NULL DEFAULT 0,
  `leaseToken` varchar(64),
  `leaseExpiresAt` timestamp NULL,
  `lastAttemptAt` timestamp NULL,
  `intent` varchar(100),
  `nextAction` text,
  `responseText` text,
  `errorCode` varchar(120),
  `promptTokens` int,
  `completionTokens` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL,
  CONSTRAINT `line_ai_manager_events_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_line_ai_manager_event` UNIQUE(`eventKey`),
  INDEX `idx_line_ai_manager_event_user` (`lineUserId`, `createdAt`),
  INDEX `idx_line_ai_manager_event_status` (`status`, `leaseExpiresAt`, `createdAt`)
);
