CREATE TABLE IF NOT EXISTS `lcm_campaigns` (
  `id` int AUTO_INCREMENT NOT NULL,
  `brandProfileId` int NOT NULL,
  `slug` varchar(220) NOT NULL,
  `title` varchar(255) NOT NULL,
  `summary` varchar(1000),
  `description` text,
  `heroImageUrl` text,
  `commissionRateMin` decimal(5,2),
  `commissionRateMax` decimal(5,2),
  `discountRateMin` decimal(5,2),
  `discountRateMax` decimal(5,2),
  `rewardNotes` text,
  `trackingMethod` enum('platform','coupon','affiliate_link','manual_report','other') NOT NULL DEFAULT 'other',
  `settlementTerms` text,
  `eligibility` text,
  `creativeGuidance` text,
  `prohibitedClaims` text,
  `sampleAvailable` boolean NOT NULL DEFAULT false,
  `samplePolicy` text,
  `applicationNotes` text,
  `startsAt` timestamp NULL,
  `endsAt` timestamp NULL,
  `status` enum('draft','published','suspended','archived') NOT NULL DEFAULT 'draft',
  `createdByAccountId` int,
  `publishedAt` timestamp NULL,
  `reviewedBy` int,
  `reviewedAt` timestamp NULL,
  `moderationReason` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `lcm_campaigns_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_lcm_campaign_slug` UNIQUE(`slug`),
  INDEX `idx_lcm_campaign_public` (`status`, `startsAt`, `endsAt`, `publishedAt`),
  INDEX `idx_lcm_campaign_brand` (`brandProfileId`, `status`, `updatedAt`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `lcm_campaign_products` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `campaignId` int NOT NULL,
  `productId` int NOT NULL,
  `displayOrder` int NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `lcm_campaign_products_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_lcm_campaign_product` UNIQUE(`campaignId`, `productId`),
  INDEX `idx_lcm_campaign_product_order` (`campaignId`, `displayOrder`),
  INDEX `idx_lcm_campaign_product_product` (`productId`, `campaignId`)
);
