import { useState } from "react";
import { Link, useLocation, useParams } from "wouter";
import { Camera, CheckCircle2, Clock3, History, LogOut, Plus, ShieldCheck, Trophy } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";

type Editor = { performanceId: number; dayNumber: number; sessionNumber: number; screenshotUrl: string | null; startedAt: string; endedAt: string; streamMinutes: string; totalGmv: string; source: "ai"|"manual"; timeStatus: string; error?: string | null; products: any[] };
const yen = new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY", maximumFractionDigits: 0 });
function toInput(value: unknown) { if (!value) return ""; const d=new Date(value as string); const j=new Date(d.getTime()+9*3600000); const p=(n:number)=>String(n).padStart(2,"0"); return `${j.getUTCFullYear()}-${p(j.getUTCMonth()+1)}-${p(j.getUTCDate())}T${p(j.getUTCHours())}:${p(j.getUTCMinutes())}`; }
function toMs(value: string) { return value ? Date.parse(`${value}:00+09:00`) : null; }
function readFile(file: File) { return new Promise<string>((resolve,reject)=>{ const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result)); reader.onerror=()=>reject(reader.error); reader.readAsDataURL(file); }); }

export default function BrandDayCreatorDashboard() {
  const { slug = "" } = useParams<{ slug: string }>();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const [dayNumber, setDayNumber] = useState(1);
  const [editor, setEditor] = useState<Editor | null>(null);
  const [localPreview, setLocalPreview] = useState<string | null>(null);
  const me = trpc.brandDay.creatorPortal.me.useQuery({ slug });
  const dashboard = trpc.brandDay.creatorPortal.dashboard.useQuery({ slug }, { enabled: Boolean(me.data) });
  const upload = trpc.brandDay.creatorPortal.beginScreenshot.useMutation({ onSuccess: result => { setEditor({ performanceId: result.performanceId, dayNumber: result.dayNumber, sessionNumber: result.sessionNumber, screenshotUrl: result.screenshotUrl, startedAt: result.startedAtJst || "", endedAt: result.endedAtJst || "", streamMinutes: String(result.streamMinutes||0), totalGmv: String(result.totalGmv||0), source: result.mode, timeStatus: result.timeStatus, error: result.error, products: result.products }); setLocalPreview(null); }, onError: error => { toast.error(error.message); setLocalPreview(null); } });
  const confirm = trpc.brandDay.creatorPortal.confirmScreenshot.useMutation({ onSuccess: async result => { toast.success(result.submissionOutcome === "reflected" ? "ランキングへ反映しました" : "管理者確認へ提出しました"); setEditor(null); setLocalPreview(null); await Promise.all([utils.brandDay.creatorPortal.dashboard.invalidate({ slug }),utils.brandDay.publicPortal.leaderboard.invalidate()]); }, onError: error => toast.error(error.message) });
  const logout = trpc.brandDay.creatorPortal.logout.useMutation({ onSuccess: () => navigate(`/brand-day/${slug}/creator/login`) });
  if (me.isLoading) return <div className="min-h-screen bg-[#090313] p-10 text-center text-white">読み込み中…</div>;
  if (!me.data) return <div className="flex min-h-screen items-center justify-center bg-[#090313] p-5"><Card className="max-w-md border-white/10 bg-white/[.06] text-center text-white"><CardContent className="p-8"><p>出場者ログインが必要です。</p><Link href={`/brand-day/${slug}/creator/login`}><Button className="mt-5 bg-amber-400 text-slate-950">ログインへ</Button></Link></CardContent></Card></div>;
  const data = dashboard.data;
  const begin = async (file: File, performanceId?: number) => { const imageData=await readFile(file); setLocalPreview(imageData); upload.mutate({ dayNumber, performanceId, imageData }); };
  const save = () => editor && confirm.mutate({ performanceId:editor.performanceId, streamMinutes:Number(editor.streamMinutes||0), startedAt:toMs(editor.startedAt), endedAt:toMs(editor.endedAt), totalGmv:Number(editor.totalGmv||0), source:editor.source, products:editor.products.map(p=>({ productName:p.productName, gmv:Number(p.gmv||0), isBrandProduct:Boolean(p.isBrandProduct), confidenceBasisPoints:Number(p.confidenceBasisPoints||0) })) });
  return <main className="min-h-screen bg-[#090313] text-white"><div className="mx-auto max-w-5xl space-y-6 px-4 py-8"><header className="flex flex-col items-start gap-4 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-amber-300">{data?.event.shortName || "BRAND DAY"}</p><h1 className="mt-2 text-2xl font-black">{me.data.tiktokName}</h1><p className="text-sm text-slate-400">{me.data.tiktokId}</p></div><div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><Link href={`/brand-day/${slug}/ranking`}><Button variant="outline" className="w-full border-white/20 px-3 text-white sm:w-auto">ランキング</Button></Link><Button variant="outline" className="w-full border-white/20 px-3 text-white sm:w-auto" onClick={()=>logout.mutate()}><LogOut className="mr-2 h-4 w-4" />ログアウト</Button></div></header>
    <section className="grid grid-cols-3 gap-3">{[[Trophy,yen.format(data?.totals.brandGmv||0),"ブランドGMV"],[Clock3,`${Math.floor((data?.totals.streamMinutes||0)/60)}時間${(data?.totals.streamMinutes||0)%60}分`,"合計配信"],[CheckCircle2,`${data?.totals.reflectedCount||0}件`,"反映済み"]].map(([Icon,value,label])=><Card key={String(label)} className="border-white/10 bg-white/[.05] text-white"><CardContent className="p-4 text-center"><Icon className="mx-auto h-5 w-5 text-amber-300" /><p className="mt-2 break-words text-lg font-black">{value as string}</p><p className="mt-1 text-[11px] text-slate-500">{label as string}</p></CardContent></Card>)}</section>
    <Card className="border-amber-300/20 bg-white/[.05] text-white"><CardHeader><CardTitle className="flex items-center gap-2"><Camera className="text-amber-300" />ライブ大画面をアップロード</CardTitle><p className="text-sm leading-6 text-slate-400">配信ごとにTikTok Shopのライブ大画面を追加してください。異なる画像は同じDAYに何枚でも登録できます。</p></CardHeader><CardContent className="space-y-4"><div className="flex gap-2 overflow-x-auto">{data?.event.days.map(day=><Button key={day.dayNumber} size="sm" variant={dayNumber===day.dayNumber?"default":"outline"} onClick={()=>{setDayNumber(day.dayNumber);setEditor(null);}}>{day.label}</Button>)}</div><label className="flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-amber-300/40 p-6 font-bold text-amber-300"><Plus className="mr-2 h-5 w-5" />新しい配信の大画面を追加<Input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)begin(f);e.target.value="";}} /></label>
    {upload.isPending && <div className="space-y-3 rounded-xl bg-violet-500/10 p-4 text-sm text-violet-200">{localPreview && <img src={localPreview} alt="選択したライブ大画面のプレビュー" className="aspect-video w-full rounded-xl bg-black object-contain" />}<p>AIが時間・GMV・商品を読み取っています…</p></div>}
    {editor && <div className="space-y-4 rounded-2xl border border-white/10 p-4">{editor.error && <p className="rounded-xl bg-amber-500/10 p-3 text-sm text-amber-200">{editor.error}</p>}{editor.screenshotUrl&&<img src={editor.screenshotUrl} alt="アップロードしたライブ大画面" className="aspect-video w-full rounded-xl bg-black object-contain"/>}<div className="grid gap-3 sm:grid-cols-2"><div><Label>開始日時（JST）</Label><Input type="datetime-local" value={editor.startedAt} onChange={e=>setEditor({...editor,startedAt:e.target.value,source:"manual"})} /></div><div><Label>終了日時（JST）</Label><Input type="datetime-local" value={editor.endedAt} onChange={e=>setEditor({...editor,endedAt:e.target.value,source:"manual"})} /></div><div><Label>配信時間（分）</Label><Input type="number" value={editor.streamMinutes} onChange={e=>setEditor({...editor,streamMinutes:e.target.value,source:"manual"})}/></div><div><Label>総GMV</Label><Input type="number" value={editor.totalGmv} onChange={e=>setEditor({...editor,totalGmv:e.target.value,source:"manual"})}/></div></div><div className="space-y-2">{editor.products.map((p,i)=><div key={i} className="grid gap-2 rounded-xl bg-white/[.04] p-3 sm:grid-cols-[1fr_140px_auto]"><Input value={p.productName} onChange={e=>setEditor({...editor,source:"manual",products:editor.products.map((x,n)=>n===i?{...x,productName:e.target.value}:x)})}/><Input type="number" value={p.gmv} onChange={e=>setEditor({...editor,source:"manual",products:editor.products.map((x,n)=>n===i?{...x,gmv:e.target.value}:x)})}/><label className="flex items-center gap-2 text-xs"><Checkbox checked={Boolean(p.isBrandProduct)} onCheckedChange={v=>setEditor({...editor,source:"manual",products:editor.products.map((x,n)=>n===i?{...x,isBrandProduct:v===true}:x)})}/>ブランド商品</label></div>)}</div><Button onClick={save} disabled={confirm.isPending} className="w-full bg-amber-400 text-slate-950">{confirm.isPending?"保存中…":editor.timeStatus==="valid"||editor.timeStatus==="partial"?"保存してランキングへ反映":"管理者確認へ提出"}</Button></div>}</CardContent></Card>
    <Card className="border-white/10 bg-white/[.04] text-white"><CardHeader><CardTitle className="flex items-center gap-2"><History className="text-fuchsia-300"/>提出履歴</CardTitle></CardHeader><CardContent className="space-y-4">{data?.performances.filter(p=>p.dayNumber===dayNumber).map(row=><div key={row.id} className="rounded-2xl border border-white/10 p-4"><div className="flex items-start justify-between"><div><p className="font-bold">配信 #{row.sessionNumber}</p><p className="text-xs text-slate-400">{row.startedAtJst||"日時未確認"} 〜 {row.endedAtJst||"—"}</p></div><span className={`rounded-full px-3 py-1 text-xs ${row.status==="reflected"?"bg-emerald-500/15 text-emerald-300":row.reviewDecision==="pending"?"bg-amber-500/15 text-amber-300":"bg-white/10 text-slate-300"}`}>{row.status==="reflected"?"ランキング反映済み":row.reviewDecision==="pending"?"管理者確認待ち":row.reviewDecision==="rejected"?"差し戻し":"下書き"}</span></div>{row.screenshotUrl&&<img src={row.screenshotUrl} alt={`配信 ${row.sessionNumber} 大画面`} className="mt-3 aspect-video w-full rounded-xl bg-black object-contain"/>}<div className="mt-3 grid grid-cols-3 gap-2 text-center"><p>{row.streamMinutes}分</p><p>{yen.format(row.totalGmv)}</p><p className="text-amber-300">{yen.format(row.brandGmv)}</p></div><label className="mt-3 flex cursor-pointer items-center justify-center rounded-xl border border-white/10 p-3 text-sm"><Input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){setDayNumber(row.dayNumber);begin(f,row.id);}e.target.value="";}}/>この配信を修正</label>{row.reviewReason&&<p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-sm text-amber-200"><ShieldCheck className="mr-2 inline h-4 w-4"/>{row.reviewReason}</p>}</div>)}{!data?.performances.some(p=>p.dayNumber===dayNumber)&&<p className="py-10 text-center text-sm text-slate-500">この日の配信実績はまだありません。</p>}</CardContent></Card>
  </div></main>;
}
