/**
 * LCM operations console: review-first, auditable marketplace administration.
 * No destructive actions; every approval/rejection is recorded by the backend.
 */
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, ArrowLeft, Building2, CheckCircle2, Clock3, Loader2, PackageCheck, PackageSearch, ShieldCheck, Store, Users, XCircle } from "lucide-react";
import { toast } from "sonner";
import { applyPageSeo } from "@/lib/pageSeo";
import { trpc } from "@/lib/trpc";
import { lcf2026ExhibitorCatalogPages } from "@/data/lcf2026ExhibitorCatalog";

type Tab = "overview" | "members" | "claims" | "brands" | "products" | "requests" | "audit";
const image = lcf2026ExhibitorCatalogPages[25]?.imageUrl || "https://www.livecommercefestival.com/favicon.ico";
const label: Record<string, string> = { pending: "審査中", approved: "承認済み", rejected: "見送り", suspended: "停止中", draft: "下書き", submitted: "確認待ち", published: "公開中", active: "管理中", preparing: "発送準備中", shipped: "発送済み", delivered: "受取済み", live_scheduled: "配信予定", completed: "完了", cancelled: "取消済み", requested: "申込済み", reviewing: "確認中", accepted: "商談承認", declined: "見送り", negotiating: "条件調整中" };

function showReviewResult(action: string, notification?: { recipientCount: number; success: boolean; errorCode: string | null } | null) {
  if (notification?.success) return toast.success(`${action}。対象者へメール通知しました`);
  if (notification?.recipientCount === 0) return toast.warning(`${action}。通知先メールがないため送信していません`);
  return toast.warning(`${action}。メール送信に失敗したため監査履歴を確認してください`);
}

export default function LcmAdmin() {
  const [tab, setTab] = useState<Tab>("overview");
  const overview = trpc.lcm.adminOverview.useQuery(undefined, { retry: false });
  const audit = trpc.lcm.adminAuditLogs.useQuery({ limit: 200 }, { enabled: tab === "audit", retry: false });
  useEffect(() => applyPageSeo({ title: "LCM 運営管理", description: "LCM会員・ブランド・商品・申請の運営管理画面です。", canonicalPath: "/lcm/admin", image, robots: "noindex, nofollow, noarchive" }), []);
  const refresh = async () => { await overview.refetch(); if (tab === "audit") await audit.refetch(); };
  const membershipReview = trpc.lcm.reviewMembership.useMutation({ onSuccess: async (data) => { showReviewResult("会員審査を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const brandReview = trpc.lcm.reviewBrand.useMutation({ onSuccess: async (data) => { showReviewResult("ブランド審査を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const claimReview = trpc.lcm.reviewBrandClaim.useMutation({ onSuccess: async (data) => { showReviewResult("ブランド管理申請を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const productReview = trpc.lcm.reviewProduct.useMutation({ onSuccess: async (data) => { showReviewResult("商品審査を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });

  const data = overview.data;
  const brandsById = useMemo(() => new Map((data?.brands || []).map((item) => [item.id, item])), [data?.brands]);
  const productsById = useMemo(() => new Map((data?.products || []).map((item) => [item.id, item])), [data?.products]);
  if (overview.isLoading) return <div className="grid min-h-screen place-items-center bg-[#0a0a0f] text-white"><Loader2 className="h-9 w-9 animate-spin text-amber-400" /></div>;
  if (overview.isError || !data) return <div className="grid min-h-screen place-items-center bg-[#0a0a0f] px-5 text-white"><div className="max-w-lg border border-white/15 bg-white/5 p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-amber-400" /><h1 className="mt-4 text-2xl font-black">LCF管理者ログインが必要です</h1><p className="mt-3 text-sm leading-7 text-white/55">LCMの審査・監査画面は管理者だけが利用できます。</p><Link href="/lcf/login?return=%2Flcm%2Fadmin" className="mt-6 inline-flex bg-amber-400 px-5 py-3 text-sm font-black text-black">管理者ログインへ</Link></div></div>;

  const pendingCounts = { members: data.memberships.filter((item) => item.status === "pending").length, claims: data.brandMembers.filter((item) => item.member.status === "pending").length, brands: data.brands.filter((item) => item.status === "submitted").length, products: data.products.filter((item) => item.status === "submitted").length };
  const tabs: Array<{ key: Tab; text: string; count?: number }> = [{ key: "overview", text: "概要" }, { key: "members", text: "会員審査", count: pendingCounts.members }, { key: "claims", text: "ブランド所有", count: pendingCounts.claims }, { key: "brands", text: "ブランド", count: pendingCounts.brands }, { key: "products", text: "商品", count: pendingCounts.products }, { key: "requests", text: "申請・商談", count: data.samples.length + data.wholesale.length }, { key: "audit", text: "監査履歴" }];
  const rejectionReason = (subject: string) => window.prompt(`${subject}の見送り・停止理由を入力してください`);

  return <div className="min-h-screen bg-[#0a0a0f] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#0a0a0f]/95 backdrop-blur"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center bg-[#f7cc35] text-sm font-black text-black">LCM</span><div><h1 className="font-black">ライブコマースマーケット管理</h1><p className="text-[11px] text-white/45">審査・申請・監査</p></div></div><Link href="/lcf/admin" className="inline-flex items-center text-xs font-black text-white/65 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" />LCF管理画面</Link></div></header><main className="mx-auto max-w-[1600px] px-5 py-7"><nav className="flex gap-2 overflow-x-auto border-b border-white/10 pb-3">{tabs.map((item) => <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`shrink-0 px-4 py-2.5 text-sm font-black ${tab === item.key ? "bg-gradient-to-r from-amber-400 to-orange-500 text-black" : "bg-white/5 text-white/55 hover:text-white"}`}>{item.text}{typeof item.count === "number" && <span className="ml-2 rounded-full bg-black/20 px-2 py-0.5 text-[10px]">{item.count}</span>}</button>)}</nav>

  {tab === "overview" && <section className="mt-7"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="会員" value={data.memberships.length} pending={pendingCounts.members} icon={<Users />} /><Metric title="ブランド" value={data.brands.length} pending={pendingCounts.brands} icon={<Store />} /><Metric title="商品" value={data.products.length} pending={pendingCounts.products} icon={<PackageSearch />} /><Metric title="サンプル・商談" value={data.samples.length + data.wholesale.length} icon={<PackageCheck />} /></div><div className="mt-8 border border-amber-400/30 bg-amber-400/5 p-6"><h2 className="text-xl font-black">今日確認する項目</h2><p className="mt-3 text-sm leading-7 text-white/55">会員 {pendingCounts.members}件、ブランド所有 {pendingCounts.claims}件、ブランド公開 {pendingCounts.brands}件、商品公開 {pendingCounts.products}件が確認待ちです。公開情報と権限を確認してから承認してください。</p></div></section>}

  {tab === "members" && <AdminList title="LCM会員"><>{data.memberships.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${item.memberType}`} title={item.displayName} status={item.status} detail={[item.businessName, `アカウントID ${item.festivalAccountId}`, item.reviewNote].filter(Boolean).join("｜")} actions={<>{item.status === "pending" && <><Action onClick={() => membershipReview.mutate({ id: item.id, status: "approved", reviewNote: null })}>承認</Action><Action danger onClick={() => { const note = rejectionReason("会員申請"); if (note) membershipReview.mutate({ id: item.id, status: "rejected", reviewNote: note }); }}>見送り</Action></>}{item.status === "approved" && <Action danger onClick={() => { const note = rejectionReason("会員"); if (note) membershipReview.mutate({ id: item.id, status: "suspended", reviewNote: note }); }}>停止</Action>}{item.status === "suspended" && <Action onClick={() => membershipReview.mutate({ id: item.id, status: "approved", reviewNote: null })}>再開</Action>}</>} />)}</></AdminList>}

  {tab === "claims" && <AdminList title="ブランド管理申請"><>{data.brandMembers.map(({ member, accountEmail, accountName }) => <ReviewCard key={member.id} eyebrow={`#${member.id}｜${member.role}`} title={brandsById.get(member.brandProfileId)?.displayName || `ブランド #${member.brandProfileId}`} status={member.status} detail={`${accountName || "名称未設定"}｜${accountEmail}`} actions={<>{member.status === "pending" && <><Action onClick={() => claimReview.mutate({ memberId: member.id, status: "active", reason: null })}>管理を承認</Action><Action danger onClick={() => { const reason = rejectionReason("ブランド管理申請"); if (reason) claimReview.mutate({ memberId: member.id, status: "rejected", reason }); }}>見送り</Action></>}</>} />)}</></AdminList>}

  {tab === "brands" && <AdminList title="ブランド公開審査"><>{data.brands.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${item.category || "カテゴリ未設定"}`} title={item.displayName} status={item.status} detail={[item.companyName, item.tagline, item.rejectionReason].filter(Boolean).join("｜")} actions={<>{["submitted", "rejected", "suspended"].includes(item.status) && <Action onClick={() => brandReview.mutate({ id: item.id, status: "published", reason: null })}>公開承認</Action>}{["submitted", "published"].includes(item.status) && <Action danger onClick={() => { const reason = rejectionReason("ブランド"); if (reason) brandReview.mutate({ id: item.id, status: item.status === "published" ? "suspended" : "rejected", reason }); }}>{item.status === "published" ? "公開停止" : "要修正"}</Action>}{item.status === "published" && <a href={`/lcm/brands/${item.slug}`} target="_blank" rel="noreferrer" className="border border-white/25 px-3 py-2 text-xs font-black">公開確認</a>}</>} />)}</></AdminList>}

  {tab === "products" && <AdminList title="商品公開審査"><>{data.products.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${brandsById.get(item.brandProfileId)?.displayName || "ブランド不明"}`} title={item.name} status={item.status} detail={[item.category, item.summary, item.wholesalePrice ? "会員限定卸条件あり" : null, item.sampleAvailable ? "サンプル受付" : null, item.rejectionReason].filter(Boolean).join("｜")} actions={<>{["submitted", "rejected", "suspended"].includes(item.status) && <Action onClick={() => productReview.mutate({ id: item.id, status: "published", reason: null })}>公開承認</Action>}{["submitted", "published"].includes(item.status) && <Action danger onClick={() => { const reason = rejectionReason("商品"); if (reason) productReview.mutate({ id: item.id, status: item.status === "published" ? "suspended" : "rejected", reason }); }}>{item.status === "published" ? "公開停止" : "要修正"}</Action>}{item.status === "published" && <a href={`/lcm/products/${item.slug}`} target="_blank" rel="noreferrer" className="border border-white/25 px-3 py-2 text-xs font-black">公開確認</a>}</>} />)}</></AdminList>}

  {tab === "requests" && <section className="mt-7 grid gap-8 xl:grid-cols-2"><AdminList title={`サンプル申請 ${data.samples.length}件`}><>{data.samples.map((item) => <ReviewCard key={item.id} eyebrow={item.requestCode} title={productsById.get(item.productId)?.name || `商品 #${item.productId}`} status={item.status} detail={[`申請者 #${item.requesterAccountId}`, item.purpose, item.trackingNumber ? `${item.trackingCarrier || "配送"} ${item.trackingNumber}` : null].filter(Boolean).join("｜")} />)}</></AdminList><AdminList title={`卸商談 ${data.wholesale.length}件`}><>{data.wholesale.map((item) => <ReviewCard key={item.id} eyebrow={item.inquiryCode} title={productsById.get(item.productId)?.name || `商品 #${item.productId}`} status={item.status} detail={[`申請者 #${item.requesterAccountId}`, `${item.requestedQuantity}点`, item.intendedUse, item.negotiatedTerms].filter(Boolean).join("｜")} />)}</></AdminList></section>}

  {tab === "audit" && <AdminList title="監査履歴"><>{audit.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></div> : (audit.data || []).map((item) => <ReviewCard key={item.id} eyebrow={`${item.entityType} #${item.entityId || "-"}`} title={item.action} status={item.actorRole} detail={`${new Date(item.createdAt).toLocaleString("ja-JP")}｜アカウント #${item.actorAccountId || "system"}`} />)}</></AdminList>}
  </main></div>;
}

function Metric({ title, value, pending = 0, icon }: { title: string; value: number; pending?: number; icon: React.ReactNode }) { return <article className="border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between text-white/45"><span className="text-xs font-black tracking-[0.12em]">{title}</span><span className="[&>svg]:h-5 [&>svg]:w-5">{icon}</span></div><p className="mt-5 text-4xl font-black">{value.toLocaleString("ja-JP")}</p>{pending > 0 && <p className="mt-2 text-xs font-black text-amber-300">確認待ち {pending}件</p>}</article>; }
function AdminList({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="border-b border-white/10 pb-3 text-xl font-black">{title}</h2><div className="mt-4 grid gap-3">{children}</div></section>; }
function ReviewCard({ eyebrow, title, status, detail, actions }: { eyebrow: string; title: string; status: string; detail?: string; actions?: React.ReactNode }) { return <article className="grid gap-4 border border-white/10 bg-white/5 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-black tracking-[0.12em] text-white/35">{eyebrow}</p><h3 className="mt-1 font-black">{title}</h3>{detail && <p className="mt-2 break-words text-xs leading-6 text-white/50">{detail}</p>}</div><div className="flex flex-wrap items-center gap-2"><span className="bg-white/10 px-2.5 py-1 text-[11px] font-black">{label[status] || status}</span>{actions}</div></article>; }
function Action({ children, danger = false, onClick }: { children: React.ReactNode; danger?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={danger ? "border border-red-400/50 px-3 py-2 text-xs font-black text-red-300" : "bg-amber-400 px-3 py-2 text-xs font-black text-black"}>{children}</button>; }
