/**
 * LCM operations console: post-publication moderation with auditable state changes.
 * No destructive actions; every suspension, restoration, and rights change is recorded by the backend.
 */
import { useEffect, useMemo, useState } from "react";
import { Link, useSearch } from "wouter";
import { Activity, AlertCircle, ArrowLeft, Building2, CheckCircle2, Clock3, Flag, Loader2, PackageCheck, PackageSearch, ShieldCheck, Star, Store, Users, XCircle } from "lucide-react";
import { toast } from "sonner";
import { buildFestivalLoginUrl, clearFestivalAdminLcmReturn } from "@/lib/festivalPortal";
import { applyPageSeo } from "@/lib/pageSeo";
import { trpc } from "@/lib/trpc";
import { lcf2026ExhibitorCatalogPages } from "@/data/lcf2026ExhibitorCatalog";

type Tab = "overview" | "members" | "creators" | "claims" | "brands" | "products" | "reviews" | "requests" | "audit";
const image = lcf2026ExhibitorCatalogPages[25]?.imageUrl || "https://www.livecommercefestival.com/favicon.ico";
const label: Record<string, string> = { pending: "確認中", provisional: "仮連携中", approved: "利用中", rejected: "利用不可", hidden: "非公開", resolved: "対応済み", dismissed: "棄却", open: "確認待ち", revoked: "権限停止", suspended: "停止中", draft: "下書き", submitted: "旧・公開確認待ち", published: "公開中", active: "管理権限確認済み", preparing: "発送準備中", shipped: "発送済み", delivered: "受取済み", live_scheduled: "配信予定", completed: "完了", cancelled: "取消済み", requested: "申込済み", reviewing: "確認中", accepted: "商談承認", declined: "見送り", negotiating: "条件調整中" };

function showReviewResult(action: string, notification?: { recipientCount: number; success: boolean; errorCode: string | null } | null) {
  if (notification?.success) return toast.success(`${action}。対象者へメール通知しました`);
  if (notification?.recipientCount === 0) return toast.warning(`${action}。通知先メールがないため送信していません`);
  return toast.warning(`${action}。メール送信に失敗したため監査履歴を確認してください`);
}

export default function LcmAdmin() {
  const search = useSearch();
  const requestedTab = new URLSearchParams(search).get("tab") as Tab | null;
  const [tab, setTab] = useState<Tab>(() => requestedTab && ["overview", "members", "creators", "claims", "brands", "products", "reviews", "requests", "audit"].includes(requestedTab) ? requestedTab : "overview");
  const adminSession = trpc.festivalAuth.me.useQuery(undefined, { retry: false });
  const isFestivalAdmin = adminSession.data?.role === "admin";
  const overview = trpc.lcm.adminOverview.useQuery(undefined, { enabled: isFestivalAdmin, retry: false });
  const audit = trpc.lcm.adminAuditLogs.useQuery({ limit: 200 }, { enabled: isFestivalAdmin && tab === "audit", retry: false });
  const returnTo = `/lcm/admin${search ? `?${search}` : ""}`;
  const adminLoginHref = buildFestivalLoginUrl(returnTo);
  useEffect(() => applyPageSeo({ title: "LCM 運営管理", description: "LCM会員・ブランド・商品・申請の事後モデレーション・監査画面です。", canonicalPath: "/lcm/admin", image, robots: "noindex, nofollow, noarchive" }), []);
  useEffect(() => clearFestivalAdminLcmReturn(window.sessionStorage), []);
  const refresh = async () => { await overview.refetch(); if (tab === "audit") await audit.refetch(); };
  const membershipReview = trpc.lcm.reviewMembership.useMutation({ onSuccess: async (data) => { showReviewResult("会員状態を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const resendMembershipEmail = trpc.lcm.resendMembershipApprovalEmail.useMutation({ onSuccess: async (data) => { showReviewResult("承認メールを再送しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const brandReview = trpc.lcm.reviewBrand.useMutation({ onSuccess: async (data) => { showReviewResult("ブランド公開状態を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const claimReview = trpc.lcm.reviewBrandClaim.useMutation({ onSuccess: async (data) => { showReviewResult("ブランド管理申請を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const companyClaimReview = trpc.lcm.reviewCompanyBrandClaims.useMutation({ onSuccess: async (data) => { showReviewResult(`${data.reviewedCount}件の会社・ブランド連携を更新しました`, data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const productReview = trpc.lcm.reviewProduct.useMutation({ onSuccess: async (data) => { showReviewResult("商品公開状態を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const creatorReview = trpc.lcm.reviewCreatorProfile.useMutation({ onSuccess: async (data) => { showReviewResult("ライブコマーサープロフィール審査を更新しました", data.notification); await refresh(); }, onError: (error) => toast.error(error.message) });
  const contentReview = trpc.lcm.moderateProductReview.useMutation({ onSuccess: async () => { toast.success("レビュー審査を更新しました"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const reviewReportResolution = trpc.lcm.resolveReviewReport.useMutation({ onSuccess: async () => { toast.success("レビュー通報を処理しました"); await refresh(); }, onError: (error) => toast.error(error.message) });

  const data = overview.data;
  const brandsById = useMemo(() => new Map((data?.brands || []).map((item) => [item.id, item])), [data?.brands]);
  const productsById = useMemo(() => new Map((data?.products || []).map((item) => [item.id, item])), [data?.products]);
  if (adminSession.isLoading || (isFestivalAdmin && overview.isLoading)) return <div className="grid min-h-screen place-items-center bg-[#0a0a0f] text-white"><Loader2 className="h-9 w-9 animate-spin text-amber-400" /></div>;
  if (!isFestivalAdmin) return <div className="grid min-h-screen place-items-center bg-[#0a0a0f] px-5 text-white"><div className="max-w-lg border border-white/15 bg-white/5 p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-amber-400" /><h1 className="mt-4 text-2xl font-black">LCF管理者ログインが必要です</h1><p className="mt-3 text-sm leading-7 text-white/55">LCMの審査・監査画面はLCF管理者だけが利用できます。社内スタッフ用ログインは使用しません。</p><Link href={adminLoginHref} className="mt-6 inline-flex bg-amber-400 px-5 py-3 text-sm font-black text-black">LCF管理者ログインへ</Link></div></div>;
  if (overview.isError || !data) return <div className="grid min-h-screen place-items-center bg-[#0a0a0f] px-5 text-white"><div className="max-w-lg border border-white/15 bg-white/5 p-8 text-center"><AlertCircle className="mx-auto h-10 w-10 text-red-300" /><h1 className="mt-4 text-2xl font-black">LCM運営データを読み込めません</h1><p className="mt-3 text-sm leading-7 text-white/55">LCF管理者ログインは確認済みです。時間をおいて再読込みしてください。</p><button type="button" onClick={() => overview.refetch()} className="mt-6 bg-amber-400 px-5 py-3 text-sm font-black text-black">再読込み</button></div></div>;

  const pendingCounts = { members: data.memberships.filter((item) => ["pending", "rejected", "suspended"].includes(item.status)).length, creators: data.creators.filter((item) => item.status === "submitted").length, claims: data.brandMembers.filter((item) => item.member.status === "pending").length, brands: data.brands.filter((item) => ["rejected", "suspended"].includes(item.status)).length, products: data.products.filter((item) => ["rejected", "suspended"].includes(item.status)).length, reviews: data.reviews.filter((item) => item.review.status === "pending").length + data.reviewReports.filter((item) => item.status === "open").length };
  const tabs: Array<{ key: Tab; text: string; count?: number }> = [{ key: "overview", text: "概要" }, { key: "members", text: "会員管理", count: pendingCounts.members }, { key: "creators", text: "ライブコマーサー", count: pendingCounts.creators }, { key: "claims", text: "既存ブランド権限", count: pendingCounts.claims }, { key: "brands", text: "ブランド管理", count: pendingCounts.brands }, { key: "products", text: "商品管理", count: pendingCounts.products }, { key: "reviews", text: "レビュー", count: pendingCounts.reviews }, { key: "requests", text: "申請・商談", count: data.samples.length + data.wholesale.length }, { key: "audit", text: "監査履歴" }];
  const rejectionReason = (subject: string) => window.prompt(`${subject}の見送り・停止理由を入力してください`);

  return <div className="min-h-screen bg-[#0a0a0f] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#0a0a0f]/95 backdrop-blur"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center bg-[#f7cc35] text-sm font-black text-black">LCM</span><div><h1 className="font-black">ライブコマースマーケット管理</h1><p className="text-[11px] text-white/45">事後モデレーション・申請・監査</p></div></div><Link href="/lcf/admin" className="inline-flex items-center text-xs font-black text-white/65 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" />LCF管理画面</Link></div></header><main className="mx-auto max-w-[1600px] px-5 py-7"><nav className="flex gap-2 overflow-x-auto border-b border-white/10 pb-3">{tabs.map((item) => <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`shrink-0 px-4 py-2.5 text-sm font-black ${tab === item.key ? "bg-gradient-to-r from-amber-400 to-orange-500 text-black" : "bg-white/5 text-white/55 hover:text-white"}`}>{item.text}{typeof item.count === "number" && <span className="ml-2 rounded-full bg-black/20 px-2 py-0.5 text-[10px]">{item.count}</span>}</button>)}</nav>

  {tab === "overview" && <section className="mt-7"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric title="会員" value={data.memberships.length} pending={pendingCounts.members} icon={<Users />} /><Metric title="ライブコマーサー" value={data.creators.length} pending={pendingCounts.creators} icon={<Activity />} /><Metric title="ブランド" value={data.brands.length} pending={pendingCounts.brands} icon={<Store />} /><Metric title="商品" value={data.products.length} pending={pendingCounts.products} icon={<PackageSearch />} /><Metric title="レビュー" value={data.reviews.length} pending={pendingCounts.reviews} icon={<Star />} /><Metric title="サンプル・商談" value={data.samples.length + data.wholesale.length} icon={<PackageCheck />} /></div><div className="mt-8 border border-amber-400/30 bg-amber-400/5 p-6"><h2 className="text-xl font-black">無料セルフ登録＋事後モデレーション</h2><p className="mt-3 text-sm leading-7 text-white/55">新規会員、本人が新しく作成するブランド、商品は事前審査なしで利用・公開できます。問題を確認した場合は、会員停止、ブランド非公開、商品非公開を理由付きで実行してください。既存LCF掲載ブランドの管理権限、ライブコマーサー公式プロフィール、レビューは、なりすまし・公開同意・取引証跡を守るため確認を維持します。</p><p className="mt-3 text-xs leading-6 text-white/45">要確認・停止中：会員 {pendingCounts.members}件、ライブコマーサー公開 {pendingCounts.creators}件、既存ブランド権限 {pendingCounts.claims}件、ブランド {pendingCounts.brands}件、商品 {pendingCounts.products}件、レビュー・通報 {pendingCounts.reviews}件</p></div></section>}

  {tab === "members" && <AdminList title="LCM会員管理"><>{data.memberships.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${item.memberType}`} title={item.displayName} status={item.status} detail={[item.businessName, `アカウントID ${item.festivalAccountId}`, item.reviewNote].filter(Boolean).join("｜")} actions={<>{item.status === "pending" && <Action onClick={() => membershipReview.mutate({ id: item.id, status: "approved", reviewNote: null })}>旧・確認待ちを利用開始</Action>}{item.status === "approved" && <><Action onClick={() => resendMembershipEmail.mutate({ id: item.id })}>利用案内メール再送</Action><Action danger onClick={() => { const note = rejectionReason("会員利用"); if (note) membershipReview.mutate({ id: item.id, status: "suspended", reviewNote: note }); }}>会員をブロック</Action></>}{["suspended", "rejected"].includes(item.status) && <Action onClick={() => membershipReview.mutate({ id: item.id, status: "approved", reviewNote: null })}>利用を再開</Action>}</>} />)}</></AdminList>}

  {tab === "creators" && <AdminList title="ライブコマーサー公式ページ審査"><>{data.creators.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${item.metricsVerification === "verified" ? "実績確認済み" : item.metricsVerification === "self_reported" ? "本人申告" : "実績未掲載"}`} title={item.displayName} status={item.status} detail={[item.agencyName, Array.isArray(item.categories) ? item.categories.join("・") : null, item.tiktokUrl, item.publicConsentAt ? "本人公開同意あり" : "公開同意なし", item.rejectionReason].filter(Boolean).join("｜")} actions={<>{["submitted", "rejected", "suspended"].includes(item.status) && <Action onClick={() => creatorReview.mutate({ id: item.id, status: "published", reason: null })}>公開承認</Action>}{item.performanceSummary && item.metricsVerification !== "verified" && ["submitted", "published"].includes(item.status) && <Action onClick={() => creatorReview.mutate({ id: item.id, status: "published", reason: null, metricsVerification: "verified" })}>実績確認＋公開</Action>}{["submitted", "published"].includes(item.status) && <Action danger onClick={() => { const reason = rejectionReason("ライブコマーサープロフィール"); if (reason) creatorReview.mutate({ id: item.id, status: item.status === "published" ? "suspended" : "rejected", reason }); }}>{item.status === "published" ? "公開停止" : "要修正"}</Action>}{item.status === "published" && <a href={`/lcm/creators/${item.slug}`} target="_blank" rel="noreferrer" className="border border-white/25 px-3 py-2 text-xs font-black">公開確認</a>}</>} />)}</></AdminList>}

  {tab === "claims" && <AdminList title="ブランド管理権限（ブランド公開とは別）"><>{data.brandMembers.map(({ member, accountEmail, accountName }) => {
    const brand = brandsById.get(member.brandProfileId);
    const companySameStatusCount = brand?.companyName ? data.brandMembers.filter((entry) => entry.member.status === member.status && entry.member.festivalAccountId === member.festivalAccountId && brandsById.get(entry.member.brandProfileId)?.companyName === brand.companyName).length : 0;
    return <ReviewCard key={member.id} eyebrow={`#${member.id}｜${member.role}`} title={brand?.displayName || `ブランド #${member.brandProfileId}`} status={member.status === "pending" ? "provisional" : member.status} detail={[brand?.companyName, accountName || "名称未設定", accountEmail, `ブランドページ：${brand ? label[brand.status] || brand.status : "未作成"}`, member.status === "pending" ? "既存LCF掲載ブランドのため、なりすまし防止の管理権限確認が必要" : null, member.status === "active" && brand?.status !== "published" ? "管理権限確認済み・ブランド側が自分で公開可能" : null, companySameStatusCount > 1 ? `同一会社 ${companySameStatusCount}件` : null].filter(Boolean).join("｜")} actions={<>{member.status === "pending" && <><Action onClick={() => claimReview.mutate({ memberId: member.id, status: "active", reason: null })}>管理権限を確認</Action>{companySameStatusCount > 1 && <Action onClick={() => companyClaimReview.mutate({ memberId: member.id, status: "active", reason: null })}>会社単位で権限確認</Action>}<Action danger onClick={() => { const reason = rejectionReason("ブランド仮連携"); if (reason) claimReview.mutate({ memberId: member.id, status: "rejected", reason }); }}>仮連携を却下</Action>{companySameStatusCount > 1 && <Action danger onClick={() => { const reason = rejectionReason("会社・ブランド仮連携"); if (reason) companyClaimReview.mutate({ memberId: member.id, status: "rejected", reason }); }}>会社単位で却下</Action>}</>}{member.status === "active" && <>{brand?.status !== "published" && <a href={`/lcm/manage?workspace=brand&brand=${member.brandProfileId}`} className="border border-white/25 px-3 py-2 text-xs font-black">ブランド入力を確認</a>}<Action danger onClick={() => { const reason = rejectionReason("ブランド管理権限"); if (reason) claimReview.mutate({ memberId: member.id, status: "revoked", reason }); }}>権限を停止</Action>{companySameStatusCount > 1 && <Action danger onClick={() => { const reason = rejectionReason("会社・ブランド管理権限"); if (reason) companyClaimReview.mutate({ memberId: member.id, status: "revoked", reason }); }}>会社単位で停止</Action>}</>}</>} />;
  })}</></AdminList>}

  {tab === "brands" && <AdminList title="ブランド公開・停止管理"><>{data.brands.map((item) => <ReviewCard key={item.id} eyebrow={`#${item.id}｜${item.category || "カテゴリ未設定"}`} title={item.displayName} status={item.status} detail={[item.companyName, item.tagline, item.status === "draft" ? "ブランド側が入力中・本人操作で公開可能" : null, item.rejectionReason].filter(Boolean).join("｜")} actions={<>{["submitted", "rejected", "suspended"].includes(item.status) && <Action onClick={() => brandReview.mutate({ id: item.id, status: "published", reason: null })}>運営として再公開</Action>}{item.status === "published" && <Action danger onClick={() => { const reason = rejectionReason("ブランド"); if (reason) brandReview.mutate({ id: item.id, status: "suspended", reason }); }}>ブランドと公開商品を停止</Action>}{item.status === "draft" && <a href={`/lcm/manage?workspace=brand&brand=${item.id}`} className="border border-white/25 px-3 py-2 text-xs font-black">入力内容を確認</a>}{item.status === "published" && <a href={`/lcm/brands/${item.slug}`} target="_blank" rel="noreferrer" className="border border-white/25 px-3 py-2 text-xs font-black">公開確認</a>}</>} />)}</></AdminList>}

  {tab === "products" && <AdminList title="商品公開・停止管理"><>{data.products.map((item) => { const brand = brandsById.get(item.brandProfileId); const brandPublished = brand?.status === "published"; return <ReviewCard key={item.id} eyebrow={`#${item.id}｜${brand?.displayName || "ブランド不明"}`} title={item.name} status={item.status} detail={[`ブランドページ：${brand ? label[brand.status] || brand.status : "未確認"}`, !brandPublished ? "親ブランドが非公開のため商品も公開対象外" : null, item.category, item.summary, item.wholesalePrice ? "会員限定卸条件あり" : null, item.sampleAvailable ? "サンプル受付" : null, item.rejectionReason].filter(Boolean).join("｜")} actions={<>{["submitted", "rejected", "suspended"].includes(item.status) && (brandPublished ? <Action onClick={() => productReview.mutate({ id: item.id, status: "published", reason: null })}>運営として再公開</Action> : <Action onClick={() => setTab("brands")}>ブランド状態を確認</Action>)}{item.status === "published" && <Action danger onClick={() => { const reason = rejectionReason("商品"); if (reason) productReview.mutate({ id: item.id, status: "suspended", reason }); }}>商品を非公開</Action>}{item.status === "published" && <a href={`/lcm/products/${item.slug}`} target="_blank" rel="noreferrer" className="border border-white/25 px-3 py-2 text-xs font-black">公開確認</a>}</>} />; })}</></AdminList>}

  {tab === "reviews" && <section className="mt-7 grid gap-8 xl:grid-cols-[1.2fr_.8fr]"><AdminList title={`レビュー審査 ${data.reviews.length}件`}><>{data.reviews.map((item) => { const review = item.review; return <ReviewCard key={review.id} eyebrow={`#${review.id}｜${productsById.get(review.productId)?.name || `商品 #${review.productId}`}｜${review.verificationSource === "sample_request" ? "サンプル受取確認済み" : "取引確認済み"}`} title={`${"★".repeat(review.rating)} ${review.title}`} status={review.status} detail={[item.reviewerName, item.reviewerType, review.body, review.moderationNote].filter(Boolean).join("｜")} actions={<>{["pending", "rejected", "hidden"].includes(review.status) && <Action onClick={() => contentReview.mutate({ id: Number(review.id), status: "published", reason: null })}>公開承認</Action>}{["pending", "published"].includes(review.status) && <Action danger onClick={() => { const reason = rejectionReason("レビュー"); if (reason) contentReview.mutate({ id: Number(review.id), status: review.status === "published" ? "hidden" : "rejected", reason }); }}>{review.status === "published" ? "公開停止" : "見送り"}</Action>}</>} />; })}</></AdminList><AdminList title={`レビュー通報 ${data.reviewReports.length}件`}><>{data.reviewReports.map((report) => { const review = data.reviews.find((item) => Number(item.review.id) === Number(report.reviewId))?.review; return <ReviewCard key={report.id} eyebrow={`通報 #${report.id}｜レビュー #${report.reviewId}`} title={review?.title || "対象レビュー"} status={report.status} detail={[report.reason, report.details, report.resolutionNote].filter(Boolean).join("｜")} actions={report.status === "open" ? <><Action danger onClick={() => { const note = window.prompt("非公開理由・対応内容を入力してください"); if (note) reviewReportResolution.mutate({ id: Number(report.id), outcome: "hide_review", note }); }}><Flag className="mr-1 inline h-3.5 w-3.5" />レビュー非公開</Action><Action onClick={() => { const note = window.prompt("通報を棄却する理由を入力してください"); if (note) reviewReportResolution.mutate({ id: Number(report.id), outcome: "dismiss", note }); }}>通報を棄却</Action></> : undefined} />; })}</></AdminList></section>}

  {tab === "requests" && <section className="mt-7 grid gap-8 xl:grid-cols-2"><AdminList title={`サンプル申請 ${data.samples.length}件`}><>{data.samples.map((item) => <ReviewCard key={item.id} eyebrow={item.requestCode} title={productsById.get(item.productId)?.name || `商品 #${item.productId}`} status={item.status} detail={[`申請者 #${item.requesterAccountId}`, item.purpose, item.trackingNumber ? `${item.trackingCarrier || "配送"} ${item.trackingNumber}` : null].filter(Boolean).join("｜")} />)}</></AdminList><AdminList title={`卸商談 ${data.wholesale.length}件`}><>{data.wholesale.map((item) => <ReviewCard key={item.id} eyebrow={item.inquiryCode} title={productsById.get(item.productId)?.name || `商品 #${item.productId}`} status={item.status} detail={[`申請者 #${item.requesterAccountId}`, `${item.requestedQuantity}点`, item.intendedUse, item.negotiatedTerms].filter(Boolean).join("｜")} />)}</></AdminList></section>}

  {tab === "audit" && <AdminList title="監査履歴"><>{audit.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></div> : (audit.data || []).map((item) => <ReviewCard key={item.id} eyebrow={`${item.entityType} #${item.entityId || "-"}`} title={item.action} status={item.actorRole} detail={`${new Date(item.createdAt).toLocaleString("ja-JP")}｜アカウント #${item.actorAccountId || "system"}`} />)}</></AdminList>}
  </main></div>;
}

function Metric({ title, value, pending = 0, icon }: { title: string; value: number; pending?: number; icon: React.ReactNode }) { return <article className="border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between text-white/45"><span className="text-xs font-black tracking-[0.12em]">{title}</span><span className="[&>svg]:h-5 [&>svg]:w-5">{icon}</span></div><p className="mt-5 text-4xl font-black">{value.toLocaleString("ja-JP")}</p>{pending > 0 && <p className="mt-2 text-xs font-black text-amber-300">要確認・停止中 {pending}件</p>}</article>; }
function AdminList({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="border-b border-white/10 pb-3 text-xl font-black">{title}</h2><div className="mt-4 grid gap-3">{children}</div></section>; }
function ReviewCard({ eyebrow, title, status, detail, actions }: { eyebrow: string; title: string; status: string; detail?: string; actions?: React.ReactNode }) { return <article className="grid gap-4 border border-white/10 bg-white/5 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-black tracking-[0.12em] text-white/35">{eyebrow}</p><h3 className="mt-1 font-black">{title}</h3>{detail && <p className="mt-2 break-words text-xs leading-6 text-white/50">{detail}</p>}</div><div className="flex flex-wrap items-center gap-2"><span className="bg-white/10 px-2.5 py-1 text-[11px] font-black">{label[status] || status}</span>{actions}</div></article>; }
function Action({ children, danger = false, onClick }: { children: React.ReactNode; danger?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={danger ? "border border-red-400/50 px-3 py-2 text-xs font-black text-red-300" : "bg-amber-400 px-3 py-2 text-xs font-black text-black"}>{children}</button>; }
