/**
 * LCJ Brain Document Generation
 * PPT生成 + Word生成 + テキスト生成
 * 
 * AI Tool Callingから呼ばれ、生成されたドキュメントをS3にアップロードして
 * ダウンロードURLを返す。
 */
import PptxGenJS from "pptxgenjs";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import { storagePut } from "./storage";
import { invokeLLM } from "./_core/llm";

// ============================================================
// PPT Generation
// ============================================================

interface PptSlide {
  title: string;
  content: string[];  // bullet points or paragraphs
  notes?: string;
}

interface PptRequest {
  title: string;
  slides: PptSlide[];
  theme?: "dark" | "light" | "corporate";
}

/**
 * Generate a PPT file from structured slide data
 */
export async function generatePPT(request: PptRequest): Promise<{ url: string; fileName: string }> {
  const pptx = new PptxGenJS();
  
  // Set presentation properties
  pptx.author = "LCJ Brain";
  pptx.title = request.title;
  pptx.subject = request.title;
  
  // Theme colors
  const themes = {
    dark: { bg: "1a1a2e", title: "e94560", text: "ffffff", accent: "7c3aed" },
    light: { bg: "ffffff", title: "1e293b", text: "334155", accent: "6366f1" },
    corporate: { bg: "f8fafc", title: "0f172a", text: "1e293b", accent: "2563eb" },
  };
  const theme = themes[request.theme || "corporate"];
  
  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: theme.bg };
  titleSlide.addText(request.title, {
    x: 0.5, y: 1.5, w: 9, h: 2,
    fontSize: 36, bold: true, color: theme.title,
    align: "center", valign: "middle",
  });
  titleSlide.addText("Generated by LCJ Brain", {
    x: 0.5, y: 4.5, w: 9, h: 0.5,
    fontSize: 12, color: theme.accent,
    align: "center",
  });
  titleSlide.addText(new Date().toLocaleDateString("ja-JP"), {
    x: 0.5, y: 5.0, w: 9, h: 0.5,
    fontSize: 11, color: theme.text,
    align: "center",
  });
  
  // Content slides
  for (const slideData of request.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.bg };
    
    // Title
    slide.addText(slideData.title, {
      x: 0.5, y: 0.3, w: 9, h: 0.8,
      fontSize: 24, bold: true, color: theme.title,
      align: "left",
    });
    
    // Divider line
    slide.addShape("rect" as any, {
      x: 0.5, y: 1.1, w: 9, h: 0.03,
      fill: { color: theme.accent },
    });
    
    // Content bullets
    const bulletText = slideData.content.map(line => ({
      text: line,
      options: { fontSize: 16, color: theme.text, bullet: { type: "bullet" as const }, breakLine: true },
    }));
    
    slide.addText(bulletText as any, {
      x: 0.5, y: 1.4, w: 9, h: 4.5,
      fontSize: 16, color: theme.text,
      valign: "top",
      paraSpaceAfter: 8,
    });
    
    // Notes
    if (slideData.notes) {
      slide.addNotes(slideData.notes);
    }
  }
  
  // Generate buffer
  const buffer = await pptx.write({ outputType: "nodebuffer" }) as Buffer;
  
  // Upload to S3
  const fileName = `${request.title.replace(/[^\w\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g, "_")}_${Date.now()}.pptx`;
  const key = `lcj-brain/documents/${fileName}`;
  const { url } = await storagePut(key, buffer, "application/vnd.openxmlformats-officedocument.presentationml.presentation");
  
  return { url, fileName };
}

// ============================================================
// Word Document Generation
// ============================================================

interface DocSection {
  heading?: string;
  headingLevel?: 1 | 2 | 3;
  paragraphs: string[];
}

interface DocRequest {
  title: string;
  sections: DocSection[];
}

/**
 * Generate a Word document from structured content
 */
export async function generateWord(request: DocRequest): Promise<{ url: string; fileName: string }> {
  const children: any[] = [];
  
  // Title
  children.push(
    new Paragraph({
      text: request.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );
  
  // Date
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `生成日: ${new Date().toLocaleDateString("ja-JP")}`,
          size: 20,
          color: "666666",
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    })
  );
  
  // Sections
  for (const section of request.sections) {
    if (section.heading) {
      const level = section.headingLevel === 1 ? HeadingLevel.HEADING_1
        : section.headingLevel === 3 ? HeadingLevel.HEADING_3
        : HeadingLevel.HEADING_2;
      children.push(
        new Paragraph({
          text: section.heading,
          heading: level,
          spacing: { before: 400, after: 200 },
        })
      );
    }
    
    for (const para of section.paragraphs) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: para, size: 22 })],
          spacing: { after: 200 },
        })
      );
    }
  }
  
  const doc = new Document({
    sections: [{
      properties: {},
      children,
    }],
  });
  
  const buffer = await Packer.toBuffer(doc);
  
  // Upload to S3
  const fileName = `${request.title.replace(/[^\w\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g, "_")}_${Date.now()}.docx`;
  const key = `lcj-brain/documents/${fileName}`;
  const { url } = await storagePut(key, Buffer.from(buffer), "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  
  return { url, fileName };
}

// ============================================================
// AI-Powered Document Content Generation
// ============================================================

/**
 * Use AI to generate structured PPT content based on user request and context data
 */
export async function aiGeneratePptContent(userRequest: string, contextData: string): Promise<PptRequest> {
  const prompt = `你是一个专业的PPT内容策划师。根据用户的需求和提供的数据，生成一个结构化的PPT内容。

用户需求: ${userRequest}

可用数据:
${contextData.substring(0, 10000)}

请生成一个JSON格式的PPT结构，包含6-12页幻灯片。格式如下:
{
  "title": "PPT标题",
  "theme": "corporate",
  "slides": [
    {
      "title": "幻灯片标题",
      "content": ["要点1", "要点2", "要点3"],
      "notes": "演讲备注（可选）"
    }
  ]
}

要求:
1. 内容专业、有条理
2. 每页3-6个要点
3. 数据引用必须来自提供的数据
4. 如果没有具体数据，用合理的框架和建议填充
5. theme可选: "dark"(深色科技风), "light"(浅色简约), "corporate"(商务蓝)
6. 只输出JSON，不要其他文字`;

  const result = await invokeLLM({
    model: "gpt-4.1-mini",
    messages: [
      { role: "system", content: "你是PPT内容生成专家。只输出有效的JSON格式。" },
      { role: "user", content: prompt },
    ],
    response_format: { type: "json_object" },
  });

  const content = result.choices?.[0]?.message?.content || "{}";
  try {
    const parsed = JSON.parse(content);
    return {
      title: parsed.title || userRequest,
      theme: parsed.theme || "corporate",
      slides: parsed.slides || [{ title: "内容", content: ["暂无内容"] }],
    };
  } catch {
    return {
      title: userRequest,
      theme: "corporate",
      slides: [{ title: "内容生成失败", content: ["请重试"] }],
    };
  }
}

/**
 * Use AI to generate structured document content
 */
export async function aiGenerateDocContent(userRequest: string, contextData: string, docType: string): Promise<{ markdown: string; docRequest: DocRequest }> {
  const prompt = `你是一个专业的文档撰写专家。根据用户的需求和提供的数据，生成一篇高质量的${docType}。

用户需求: ${userRequest}

可用数据:
${contextData.substring(0, 10000)}

请生成一个JSON格式的文档结构。格式如下:
{
  "title": "文档标题",
  "markdown": "完整的Markdown格式文档内容（用于直接显示）",
  "sections": [
    {
      "heading": "章节标题",
      "headingLevel": 2,
      "paragraphs": ["段落1内容", "段落2内容"]
    }
  ]
}

要求:
1. markdown字段包含完整的Markdown格式文档（标题、段落、列表、表格等）
2. sections字段是结构化版本（用于生成Word文档）
3. 内容专业、有深度、有条理
4. 数据引用必须来自提供的数据
5. 如果是BD话术，要有具体的话术示例和场景
6. 如果是品牌提案，要有数据支撑和合作方案
7. 只输出JSON，不要其他文字`;

  const result = await invokeLLM({
    model: "gpt-4.1-mini",
    messages: [
      { role: "system", content: "你是专业文档撰写专家。只输出有效的JSON格式。" },
      { role: "user", content: prompt },
    ],
    response_format: { type: "json_object" },
  });

  const content = result.choices?.[0]?.message?.content || "{}";
  try {
    const parsed = JSON.parse(content);
    return {
      markdown: parsed.markdown || "# 文档生成失败\n请重试。",
      docRequest: {
        title: parsed.title || userRequest,
        sections: parsed.sections || [{ paragraphs: ["内容生成失败，请重试。"] }],
      },
    };
  } catch {
    return {
      markdown: "# 文档生成失败\n请重试。",
      docRequest: {
        title: userRequest,
        sections: [{ paragraphs: ["内容生成失败，请重试。"] }],
      },
    };
  }
}
