import { createHash } from "node:crypto";

export type PerformanceTemplateSeed = {
  templateCode: string;
  responsibilityLine: string;
  roleName: string;
  triggerCycle: string;
  title: string;
  defaultDeadline: string;
  evidenceSource: string;
  completionCondition: string;
  reviewerRole: string;
  primaryDimension: string;
  sourceAdapter: string;
  defaultStatus: "draft" | "shadow";
};

export const PERFORMANCE_TEMPLATE_CATALOG: PerformanceTemplateSeed[] = [
  {
    "templateCode": "ALL-D01",
    "responsibilityLine": "全员",
    "roleName": "日报员工",
    "triggerCycle": "工作日",
    "title": "提交当日日报",
    "defaultDeadline": "员工当地日期当日内（23:59:59前）",
    "evidenceSource": "/master/reports",
    "completionCondition": "有事实/结果/问题/下一步且不是空模板",
    "reviewerRole": "直属负责人",
    "primaryDimension": "完成度/及时性/质量",
    "sourceAdapter": "daily_report",
    "defaultStatus": "shadow"
  },
  {
    "templateCode": "ALL-D02",
    "responsibilityLine": "全员",
    "roleName": "任务负责人",
    "triggerCycle": "任务触发",
    "title": "接受任务并更新进度",
    "defaultDeadline": "分配后1个工作日",
    "evidenceSource": "/master/tasks",
    "completionCondition": "状态/进度/截止/负责人完整",
    "reviewerRole": "任务验收人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "task",
    "defaultStatus": "shadow"
  },
  {
    "templateCode": "ALL-D03",
    "responsibilityLine": "全员",
    "roleName": "问题责任人",
    "triggerCycle": "问题触发",
    "title": "说明原因方案并推进关闭",
    "defaultDeadline": "按问题SLA",
    "evidenceSource": "/master/issues",
    "completionCondition": "有owner/影响/动作/验证/关闭记录",
    "reviewerRole": "问题发起人或部门负责人",
    "primaryDimension": "闭环",
    "sourceAdapter": "issue",
    "defaultStatus": "shadow"
  },
  {
    "templateCode": "ALL-D04",
    "responsibilityLine": "全员",
    "roleName": "早会参与者",
    "triggerCycle": "工作日",
    "title": "完成个人朗读并参加团队早会",
    "defaultDeadline": "员工当地日期当日内（23:59:59前）",
    "evidenceSource": "/master/morning-meeting",
    "completionCondition": "本人记录与团队参与snapshot存在",
    "reviewerRole": "直属负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "morning_meeting",
    "defaultStatus": "shadow"
  },
  {
    "templateCode": "OPS-C01",
    "responsibilityLine": "运营部-直播中控",
    "roleName": "中控负责人/执行",
    "triggerCycle": "每场直播",
    "title": "完成场次中控准备与交接",
    "defaultDeadline": "开播前60分钟",
    "evidenceSource": "主播司令塔/Rundown/任务",
    "completionCondition": "账号/商品/价格/库存/脚本/应急联系人齐全",
    "reviewerRole": "直播运营负责人",
    "primaryDimension": "完成度/准确闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-C02",
    "responsibilityLine": "运营部-直播中控",
    "roleName": "中控负责人/执行",
    "triggerCycle": "每场直播",
    "title": "记录直播异常与处理结果",
    "defaultDeadline": "发生后30分钟内",
    "evidenceSource": "/master/issues",
    "completionCondition": "异常时间/影响/处理/恢复/责任人齐全",
    "reviewerRole": "直播运营负责人",
    "primaryDimension": "及时性/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-L01",
    "responsibilityLine": "运营部-直播运营",
    "roleName": "专属运营",
    "triggerCycle": "每月",
    "title": "提交达人月度直播计划",
    "defaultDeadline": "每月25日前完成次月",
    "evidenceSource": "/master/livers-dashboard/任务",
    "completionCondition": "场次/主题/商品/目标/所需资源齐全",
    "reviewerRole": "直播运营组负责人",
    "primaryDimension": "完成度/质量",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-L02",
    "responsibilityLine": "运营部-直播运营",
    "roleName": "专属运营",
    "triggerCycle": "每场直播",
    "title": "完成选品价格赠品和Rundown",
    "defaultDeadline": "开播前24小时",
    "evidenceSource": "选品中心/Rundown",
    "completionCondition": "商品SKU/价格/库存/机制/脚本已确认",
    "reviewerRole": "直播运营组负责人",
    "primaryDimension": "完成度/及时性/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-L03",
    "responsibilityLine": "运营部-直播运营",
    "roleName": "专属运营",
    "triggerCycle": "每场直播",
    "title": "登记直播结果并完成复盘",
    "defaultDeadline": "结束后次日18:00",
    "evidenceSource": "主播登记/主播司令塔",
    "completionCondition": "GMV/订单/流量/问题/优化动作齐全",
    "reviewerRole": "直播运营组负责人",
    "primaryDimension": "完成度/质量/闭环",
    "sourceAdapter": "livestream_registration",
    "defaultStatus": "shadow"
  },
  {
    "templateCode": "OPS-S01",
    "responsibilityLine": "运营部-店铺运营",
    "roleName": "店铺负责人",
    "triggerCycle": "每日",
    "title": "处理订单库存售后和异常",
    "defaultDeadline": "当日结束前",
    "evidenceSource": "/master/store-management",
    "completionCondition": "关键异常有记录和处理状态",
    "reviewerRole": "店铺运营组负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-S02",
    "responsibilityLine": "运营部-店铺运营",
    "roleName": "店铺负责人",
    "triggerCycle": "每周",
    "title": "提交店铺周复盘",
    "defaultDeadline": "每周一12:00",
    "evidenceSource": "店铺管理/销售检查",
    "completionCondition": "销售/订单/退货/广告/库存/下周动作齐全",
    "reviewerRole": "店铺运营组负责人",
    "primaryDimension": "质量/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-V01",
    "responsibilityLine": "短视频运营组",
    "roleName": "负责人/成员",
    "triggerCycle": "每条视频",
    "title": "登记视频与制作发布信息",
    "defaultDeadline": "发布当日",
    "evidenceSource": "/master/short-video",
    "completionCondition": "链接/账号/制作人/发布时间齐全",
    "reviewerRole": "短视频负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "OPS-V02",
    "responsibilityLine": "短视频运营组",
    "roleName": "负责人/成员",
    "triggerCycle": "次日",
    "title": "补录前一日视频与账号经营数据",
    "defaultDeadline": "次日18:00",
    "evidenceSource": "/master/short-video?tab=daily",
    "completionCondition": "播放互动与账号GMV/订单分区记录",
    "reviewerRole": "短视频负责人",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "ADS-01",
    "responsibilityLine": "广告运营与投流",
    "roleName": "投流负责人/执行",
    "triggerCycle": "每次投放",
    "title": "登记预算目标账户素材和归因对象",
    "defaultDeadline": "投放前",
    "evidenceSource": "/master/ad-form-submissions",
    "completionCondition": "预算/目标/素材/直播场次或店铺关联齐全",
    "reviewerRole": "投流组负责人",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "ADS-02",
    "responsibilityLine": "广告运营与投流",
    "roleName": "投流负责人/执行",
    "triggerCycle": "每日投放",
    "title": "更新消耗流量成交与异常",
    "defaultDeadline": "当日结束前",
    "evidenceSource": "/master/ad-dashboard",
    "completionCondition": "消耗/归因销售/ROAS/异常与动作齐全",
    "reviewerRole": "投流组负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "ADS-03",
    "responsibilityLine": "广告运营与投流",
    "roleName": "投流负责人",
    "triggerCycle": "每个计划结束",
    "title": "完成优化复盘",
    "defaultDeadline": "结束后2个工作日",
    "evidenceSource": "/master/ad-dashboard/日报",
    "completionCondition": "预算变更/结果/原因/下次方案齐全",
    "reviewerRole": "运营管理线",
    "primaryDimension": "质量/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-L01",
    "responsibilityLine": "商务部-达播招商",
    "roleName": "品牌主负责人",
    "triggerCycle": "线索触发",
    "title": "建立品牌线索并记录关键条件",
    "defaultDeadline": "首次接触当日",
    "evidenceSource": "/master/recruitment/brands",
    "completionCondition": "联系人/品牌/需求/阶段/下一步齐全",
    "reviewerRole": "达播招商负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-L02",
    "responsibilityLine": "商务部-达播招商",
    "roleName": "品牌主负责人",
    "triggerCycle": "合作确认",
    "title": "完成运营交接包",
    "defaultDeadline": "确认后1个工作日",
    "evidenceSource": "品牌管理/任务",
    "completionCondition": "商品/价格/佣金/赠品/库存/排期/责任人齐全",
    "reviewerRole": "达播招商负责人",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-L03",
    "responsibilityLine": "商务部-达播招商",
    "roleName": "部门负责人",
    "triggerCycle": "每月",
    "title": "维护部门合作品牌KPI",
    "defaultDeadline": "每月末",
    "evidenceSource": "/master/recruitment",
    "completionCondition": "去重后的有效合作品牌数及贡献人完整",
    "reviewerRole": "经营统筹",
    "primaryDimension": "结果看板（不直接占个人系统分）",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-C01",
    "responsibilityLine": "商务部-达人分销",
    "roleName": "达人BD",
    "triggerCycle": "每日",
    "title": "更新达人触达与回复状态",
    "defaultDeadline": "当日结束前",
    "evidenceSource": "/master/influencer-bd",
    "completionCondition": "达人唯一标识/阶段/沟通证据/下一步齐全",
    "reviewerRole": "达人分销负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-C02",
    "responsibilityLine": "商务部-达人分销",
    "roleName": "达人BD",
    "triggerCycle": "寄样触发",
    "title": "登记寄样排期和合作结果",
    "defaultDeadline": "状态变化当日",
    "evidenceSource": "/master/influencer-bd/sample-requests",
    "completionCondition": "寄样/物流/排期/结果/失败原因齐全",
    "reviewerRole": "达人分销负责人",
    "primaryDimension": "闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-B01",
    "responsibilityLine": "商务部-品牌分销",
    "roleName": "渠道负责人",
    "triggerCycle": "客户触发",
    "title": "建立渠道客户与合作需求",
    "defaultDeadline": "首次沟通当日",
    "evidenceSource": "品牌管理/名片/任务",
    "completionCondition": "客户类型/需求/负责人/阶段/下一步齐全",
    "reviewerRole": "品牌分销负责人",
    "primaryDimension": "完成度/质量",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BD-B02",
    "responsibilityLine": "商务部-品牌分销",
    "roleName": "渠道负责人",
    "triggerCycle": "报价或订单触发",
    "title": "推进报价样品订单付款发货",
    "defaultDeadline": "按节点",
    "evidenceSource": "任务/库存/财务",
    "completionCondition": "每个节点有状态/日期/证据/异常",
    "reviewerRole": "品牌分销负责人",
    "primaryDimension": "及时性/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "EVENT-01",
    "responsibilityLine": "商务部-活动运营",
    "roleName": "活动项目负责人",
    "triggerCycle": "项目启动",
    "title": "建立目标预算里程碑和分工",
    "defaultDeadline": "立项后2个工作日",
    "evidenceSource": "/master/festival/任务",
    "completionCondition": "目标/预算/时间表/owner/风险齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "完成度/质量",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "EVENT-02",
    "responsibilityLine": "商务部-活动运营",
    "roleName": "项目成员",
    "triggerCycle": "里程碑触发",
    "title": "完成分配的活动交付",
    "defaultDeadline": "按里程碑",
    "evidenceSource": "/master/festival/任务",
    "completionCondition": "交付物与验收人确认",
    "reviewerRole": "项目负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "EVENT-03",
    "responsibilityLine": "商务部-活动运营",
    "roleName": "活动项目负责人",
    "triggerCycle": "项目结束",
    "title": "提交结果费用问题和复盘",
    "defaultDeadline": "结束后5个工作日",
    "evidenceSource": "/master/festival/finance/issues",
    "completionCondition": "结果/费用/问题/改进/责任人齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "质量/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BRAND-01",
    "responsibilityLine": "品牌责任矩阵",
    "roleName": "品牌负责人",
    "triggerCycle": "每月",
    "title": "更新品牌经营计划与关键决策",
    "defaultDeadline": "每月5日前",
    "evidenceSource": "/master/brands",
    "completionCondition": "定位/产品/价格/库存风险/目标齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "完成度/质量",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BRAND-02",
    "responsibilityLine": "品牌责任矩阵",
    "roleName": "达人建联负责人",
    "triggerCycle": "每周",
    "title": "更新该品牌达人建联与寄样进度",
    "defaultDeadline": "每周一12:00",
    "evidenceSource": "/master/influencer-bd",
    "completionCondition": "达人去重/阶段/证据/下一步齐全",
    "reviewerRole": "品牌负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "BRAND-03",
    "responsibilityLine": "品牌责任矩阵",
    "roleName": "运营负责人",
    "triggerCycle": "每场/每周",
    "title": "更新上架直播活动与数据复盘",
    "defaultDeadline": "事件后1个工作日",
    "evidenceSource": "选品/店铺/主播司令塔",
    "completionCondition": "上架/库存/活动/结果/优化动作齐全",
    "reviewerRole": "品牌负责人",
    "primaryDimension": "完成度/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "SEA-01",
    "responsibilityLine": "海外店铺",
    "roleName": "筹备负责人",
    "triggerCycle": "筹备期每周",
    "title": "更新开店清单与阻塞问题",
    "defaultDeadline": "每周一12:00",
    "evidenceSource": "任务/问题/店铺管理",
    "completionCondition": "资质/账号/商品/库存/物流/人员节点齐全",
    "reviewerRole": "CEO运营线",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "SEA-02",
    "responsibilityLine": "海外店铺",
    "roleName": "店铺负责人",
    "triggerCycle": "启用后每日",
    "title": "处理商品订单库存售后与经营异常",
    "defaultDeadline": "当日结束前",
    "evidenceSource": "店铺管理",
    "completionCondition": "市场与店铺维度记录完整",
    "reviewerRole": "CEO运营线",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "SEA-03",
    "responsibilityLine": "海外店铺",
    "roleName": "店铺负责人",
    "triggerCycle": "启用后每周",
    "title": "提交市场经营复盘",
    "defaultDeadline": "每周一12:00",
    "evidenceSource": "店铺/短视频/广告",
    "completionCondition": "销售/订单/内容/广告/库存/动作齐全",
    "reviewerRole": "CEO运营线",
    "primaryDimension": "质量/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "PROC-01",
    "responsibilityLine": "采购部",
    "roleName": "采购负责人",
    "triggerCycle": "采购触发",
    "title": "更新采购进度与预计到货",
    "defaultDeadline": "状态变化当日",
    "evidenceSource": "selection-center采购/到货需求",
    "completionCondition": "供应商/数量/成本/预计到货/状态齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "PROC-02",
    "responsibilityLine": "采购部",
    "roleName": "采购负责人",
    "triggerCycle": "异常触发",
    "title": "登记缺货延期成本或样品异常",
    "defaultDeadline": "发现后2小时",
    "evidenceSource": "/master/issues/库存/样品",
    "completionCondition": "影响/原因/应对/新日期/通知对象齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "及时性/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "FIN-01",
    "responsibilityLine": "财务部",
    "roleName": "财务负责人/成员",
    "triggerCycle": "每日",
    "title": "完成现金流票据和待确认登记",
    "defaultDeadline": "当日或业务SLA",
    "evidenceSource": "/master/finance/receipts",
    "completionCondition": "方向/分类/金额/币种/凭证/状态齐全",
    "reviewerRole": "财务负责人",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "FIN-02",
    "responsibilityLine": "财务部",
    "roleName": "财务负责人/成员",
    "triggerCycle": "每月",
    "title": "完成对账结算和未决清单",
    "defaultDeadline": "月结日期",
    "evidenceSource": "/master/finance",
    "completionCondition": "差异/负责人/处理期限/关闭状态齐全",
    "reviewerRole": "经营统筹或二次复核人",
    "primaryDimension": "准确/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "HR-01",
    "responsibilityLine": "人事部",
    "roleName": "HR负责人",
    "triggerCycle": "人员变动触发",
    "title": "更新入离职部门岗位和系统权限",
    "defaultDeadline": "生效日前",
    "evidenceSource": "/master/hr/system-users",
    "completionCondition": "在职状态/岗位/生效日/账号权限一致",
    "reviewerRole": "经营统筹",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "HR-02",
    "responsibilityLine": "人事部",
    "roleName": "HR负责人",
    "triggerCycle": "例外触发",
    "title": "登记休假系统故障负责人变更等积分例外",
    "defaultDeadline": "事实确认当日",
    "evidenceSource": "HR/员工日程/问题单",
    "completionCondition": "原因/范围/起止/批准人齐全",
    "reviewerRole": "经营统筹",
    "primaryDimension": "准确/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "DES-01",
    "responsibilityLine": "设计部",
    "roleName": "设计负责人/执行",
    "triggerCycle": "需求触发",
    "title": "确认需求范围版本和交付时间",
    "defaultDeadline": "受理后1个工作日",
    "evidenceSource": "任务/问题/设计需求",
    "completionCondition": "文字/尺寸/语言/场景/截止/验收人齐全",
    "reviewerRole": "需求方负责人",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "DES-02",
    "responsibilityLine": "设计部",
    "roleName": "设计负责人/执行",
    "triggerCycle": "交付触发",
    "title": "提交最终文件和版本记录",
    "defaultDeadline": "截止前",
    "evidenceSource": "任务/文件归档",
    "completionCondition": "文件链接/版本/用途/验收状态齐全",
    "reviewerRole": "需求方负责人",
    "primaryDimension": "完成度/及时性",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "IT-01",
    "responsibilityLine": "IT部",
    "roleName": "IT负责人/执行",
    "triggerCycle": "故障触发",
    "title": "登记影响范围原因修复和验证",
    "defaultDeadline": "按SLA",
    "evidenceSource": "/master/issues/control",
    "completionCondition": "时间线/影响/修复/验证/复盘齐全",
    "reviewerRole": "CEO运营线",
    "primaryDimension": "及时性/闭环",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  },
  {
    "templateCode": "IT-02",
    "responsibilityLine": "IT部",
    "roleName": "IT负责人/执行",
    "triggerCycle": "账号权限变更",
    "title": "完成申请审批执行和复核",
    "defaultDeadline": "生效前",
    "evidenceSource": "/master/account-management/system-users",
    "completionCondition": "申请人/批准人/权限差异/执行时间齐全",
    "reviewerRole": "CEO运营线",
    "primaryDimension": "完成度/准确",
    "sourceAdapter": "manual",
    "defaultStatus": "draft"
  }
];

export const PERFORMANCE_TEMPLATE_CATALOG_HASH = createHash("sha256")
  .update(JSON.stringify(PERFORMANCE_TEMPLATE_CATALOG))
  .digest("hex");

export const PERFORMANCE_RULE_VERSION_CODE = "LCJ-PERFORMANCE-V2-SHADOW";
