import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ja" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Japanese translations
const jaTranslations: Record<string, string> = {
  // Navigation
  "nav.dashboard": "ダッシュボード",
  "nav.tasks": "タスク一覧",
  "nav.reports": "レポート",
  "nav.reportStaff": "レポートスタッフ",
  "nav.staff": "担当者名簿",
  "nav.masterControl": "マスターコントロール",
  "nav.reportAnalysis": "AI分析",
  "nav.brands": "ブランド管理",
  "nav.businessCards": "名刺管理",
  "nav.line": "LINE管理",
  "nav.lineFollowUps": "フォローアップ",
  "nav.pendingResponses": "要対応",
  "nav.calendar": "カレンダー",
  "nav.livers": "ライバー管理",
  "nav.logout": "ログアウト",
  
  // Dashboard
  "dashboard.title": "ダッシュボード",
  "dashboard.inProgress": "進行中",
  "dashboard.completed": "完了",
  "dashboard.overdue": "期限切れ",
  "dashboard.pending": "未着手",
  "dashboard.staffList": "担当者一覧",
  "dashboard.recentTasks": "最近のタスク",
  "dashboard.noTasks": "タスクがありません",
  "dashboard.viewAll": "すべて表示",
  "dashboard.createTask": "新規タスク作成",
  "dashboard.dailyReport": "デイリーレポートを作成",
  
  // Tasks
  "tasks.title": "タスク一覧",
  "tasks.create": "新規タスク作成",
  "tasks.search": "検索",
  "tasks.filter": "フィルター",
  "tasks.status": "ステータス",
  "tasks.staff": "担当者",
  "tasks.deadline": "期限",
  "tasks.detail": "詳細",
  "tasks.noDeadline": "期限なし",
  "tasks.all": "すべて",
  "tasks.statusPending": "未着手",
  "tasks.statusInProgress": "進行中",
  "tasks.statusCompleted": "完了",
  "tasks.statusCancelled": "キャンセル",
  "tasks.clearFilters": "フィルターをクリア",
  "tasks.results": "件が該当しました",
  "tasks.noResults": "該当するタスクがありません",
  
  // Task Create
  "taskCreate.title": "新規タスク作成",
  "taskCreate.screenshots": "スクリーンショット",
  "taskCreate.uploadHint": "最大4枚までアップロード可能",
  "taskCreate.selectStaff": "担当者を選択",
  "taskCreate.deadline": "期限（任意）",
  "taskCreate.notes": "メモ（任意）",
  "taskCreate.submit": "タスクを作成",
  "taskCreate.submitting": "作成中...",
  
  // Task Detail
  "taskDetail.title": "タスク詳細",
  "taskDetail.taskId": "タスクID",
  "taskDetail.status": "ステータス",
  "taskDetail.staff": "担当者",
  "taskDetail.deadline": "期限",
  "taskDetail.createdAt": "作成日時",
  "taskDetail.updatedAt": "更新日時",
  "taskDetail.screenshots": "スクリーンショット",
  "taskDetail.notes": "メモ",
  "taskDetail.sendReminder": "リマインドメール送信",
  "taskDetail.markComplete": "完了にする",
  "taskDetail.reminderHistory": "リマインド履歴",
  "taskDetail.emailOpened": "開封済み",
  "taskDetail.emailNotOpened": "未開封",
  
  // Reports
  "reports.title": "レポート",
  "reports.create": "新規レポートを作成",
  "reports.list": "レポート一覧",
  "reports.staff": "スタッフ",
  "reports.date": "日付",
  "reports.content": "業務内容",
  "reports.issues": "気付き・問題・理由",
  "reports.remarks": "備考",
  "reports.updatedAt": "更新日時",
  "reports.actions": "操作",
  "reports.noReports": "レポートがありません",
  "reports.clearFilters": "フィルターをクリア",
  "reports.clearFilter": "フィルターをクリア",
  "reports.results": "件が該当しました",
  "reports.searchResults": "検索結果",
  "reports.prevMonth": "前月",
  "reports.lastMonth": "前月",
  "reports.thisMonth": "今月",
  "reports.days": "日中",
  "reports.items": "件",
  "reports.country": "国",
  "reports.all": "全て",
  "reports.allCountries": "全ての国",
  "reports.allStaff": "全てのスタッフ",
  "reports.japan": "日本",
  "reports.china": "中国",
  "reports.notLinked": "未紐付け",
  "reports.noTasks": "タスクなし",
  "reports.noStaffInCountry": "この国のスタッフはいません",
  "reports.workContent": "業務内容",
  "reports.deleted": "レポートを削除しました",
  "reports.deleteConfirm": "レポートを削除しますか？",
  "reports.deleteWarning": "この操作は取り消せません。本当に削除しますか？",
  "reports.cancel": "キャンセル",
  "reports.delete": "削除",
  "reports.deleting": "削除中...",
  "reports.chatCreate": "チャットで作成",
  "reports.detail": "レポート詳細",
  "reports.reportDetail": "日報詳細",
  "reports.notFound": "日報が見つかりません",
  "reports.observations": "気付き・問題・理由",
  "reports.notes": "備考",
  
  // Followups
  "followups.title": "フォローアップ待ち",
  "followups.overdue": "期限超過",
  "followups.pending": "対応待ち",
  "followups.completed": "対応済み",
  "followups.cancelled": "キャンセル",
  "followups.item": "項目",
  "followups.category": "カテゴリ",
  "followups.dueDate": "期限",
  "followups.staff": "担当者",
  "followups.reportDate": "日報日付",
  "followups.status": "ステータス",
  "followups.actions": "操作",
  "followups.markComplete": "対応済みにする",
  "followups.markCancelled": "キャンセル",
  "followups.noFollowups": "フォローアップ待ちの項目はありません",
  "followups.overdueWarning": "2日以上経過",
  "followups.extractFromReport": "この日報からフォローアップを抽出",
  "followups.extracting": "抽出中...",
  "followups.extracted": "フォローアップを抽出しました",
  "followups.batchExtract": "一括抽出",
  "followups.batchExtractDesc": "過去7日間の日報からフォローアップを抽出",
  "followups.noOverdue": "現在フォローアップ待ちの項目はありません。「一括抽出」ボタンで日報からフォローアップ項目を抽出できます。",
  "followups.resultTitle": "結果を記録",
  "followups.resultCategory": "結果",
  "followups.resultNote": "メモ",
  "followups.resultNotePlaceholder": "結果の詳細を入力...",
  "followups.nextActionSuggestion": "AI提案: 次のアクション",
  "followups.willCreate": "作成する",
  "followups.skip": "スキップ",
  "followups.complete": "完了",
  "followups.suggestingNextAction": "次のアクションを提案中...",
  "followups.nextActionCreated": "次のアクションを作成しました",
  "followups.viewReport": "日報を見る",
  "followups.completedTab": "完了済み",
  "followups.allStaff": "全スタッフ",
  "followups.noCompleted": "完了済みのフォローアップはありません",
  "followups.note": "メモ",
  // Result categories
  "followups.result.closed": "成約",
  "followups.result.closedDesc": "契約・取引が成立した",
  "followups.result.continued": "継続",
  "followups.result.continuedDesc": "次のアクションが必要",
  "followups.result.pending": "保留",
  "followups.result.pendingDesc": "一時的に対応を保留",
  "followups.result.lost": "失注",
  "followups.result.lostDesc": "契約・取引が不成立",
  "followups.result.done": "完了",
  "followups.result.doneDesc": "対応が完了した",
  
  // Report Form
  "reportForm.createTitle": "新規レポート作成",
  "reportForm.editTitle": "レポート編集",
  "reportForm.staff": "スタッフ",
  "reportForm.selectStaff": "スタッフを選択",
  "reportForm.addNewStaff": "新規スタッフを追加",
  "reportForm.newStaffName": "新規スタッフ名",
  "reportForm.country": "国",
  "reportForm.date": "日付",
  "reportForm.content": "業務内容",
  "reportForm.contentPlaceholder": "今日の業務内容を入力してください",
  "reportForm.issues": "気付き・問題・理由",
  "reportForm.issuesPlaceholder": "気付いたことや問題点を入力してください",
  "reportForm.remarks": "備考",
  "reportForm.remarksPlaceholder": "その他の備考を入力してください",
  "reportForm.submit": "保存",
  "reportForm.submitting": "保存中...",
  "reportForm.back": "戻る",
  
  // Report Staff Management
  "reportStaff.title": "レポートスタッフ管理",
  "reportStaff.description": "日報用のスタッフを管理し、担当者名簿との紐付けを設定します",
  "reportStaff.add": "新規追加",
  "reportStaff.list": "レポートスタッフ一覧",
  "reportStaff.name": "名前",
  "reportStaff.country": "国",
  "reportStaff.linkedStaff": "紐付け担当者",
  "reportStaff.taskProgress": "タスク進捗",
  "reportStaff.status": "ステータス",
  "reportStaff.actions": "操作",
  "reportStaff.notLinked": "未紐付け",
  "reportStaff.active": "有効",
  "reportStaff.inactive": "無効",
  "reportStaff.noStaff": "レポートスタッフがいません",
  "reportStaff.addTitle": "レポートスタッフを追加",
  "reportStaff.editTitle": "レポートスタッフを編集",
  "reportStaff.linkTitle": "担当者との紐付け",
  "reportStaff.linkDescription": "を担当者名簿のスタッフと紐付けます。紐付けると、日報からタスクの進捗を確認できるようになります。",
  "reportStaff.selectLinkedStaff": "紐付ける担当者",
  "reportStaff.noLink": "紐付けなし",
  "reportStaff.save": "保存",
  "reportStaff.saving": "保存中...",
  "reportStaff.saveLink": "紐付けを保存",
  "reportStaff.cancel": "キャンセル",
  "reportStaff.deleteConfirm": "このレポートスタッフを削除しますか？関連する日報も削除される可能性があります。",
  "reportStaff.loading": "読込中...",
  "reportStaff.noTasks": "タスクなし",
  
  // Staff Management
  "staffMgmt.title": "担当者名簿",
  "staffMgmt.add": "新規追加",
  "staffMgmt.name": "名前",
  "staffMgmt.email": "メールアドレス",
  "staffMgmt.department": "部署",
  "staffMgmt.country": "国",
  "staffMgmt.status": "ステータス",
  "staffMgmt.actions": "操作",
  "staffMgmt.active": "有効",
  "staffMgmt.inactive": "無効",
  "staffMgmt.noStaff": "担当者がいません",
  "staffMgmt.addTitle": "担当者を追加",
  "staffMgmt.editTitle": "担当者を編集",
  "staffMgmt.save": "保存",
  "staffMgmt.saving": "保存中...",
  "staffMgmt.cancel": "キャンセル",
  "staffMgmt.deleteConfirm": "この担当者を削除しますか？",
  
  // Login
  "login.title": "ログイン",
  "login.subtitle": "業務自動化システムにログイン",
  "login.email": "メールアドレス",
  "login.password": "パスワード",
  "login.submit": "ログイン",
  "login.submitting": "ログイン中...",
  "login.register": "新規登録はこちら",
  "login.error": "ログインに失敗しました",
  
  // Register
  "register.title": "新規登録",
  "register.subtitle": "アカウントを作成",
  "register.name": "名前",
  "register.email": "メールアドレス",
  "register.password": "パスワード",
  "register.confirmPassword": "パスワード確認",
  "register.submit": "登録",
  "register.submitting": "登録中...",
  "register.login": "ログインはこちら",
  "register.error": "登録に失敗しました",
  
  // Common
  "common.loading": "読み込み中...",
  "common.error": "エラーが発生しました",
  "common.save": "保存",
  "common.cancel": "キャンセル",
  "common.delete": "削除",
  "common.edit": "編集",
  "common.add": "追加",
  "common.search": "検索",
  "common.filter": "フィルター",
  "common.all": "すべて",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.confirm": "確認",
  "common.back": "戻る",
  "common.next": "次へ",
  "common.previous": "前へ",
  "common.language": "言語",
  
  // Point System
  "nav.points": "ポイント管理",
  "nav.receipts": "レシート管理",
  "nav.lineReceipts": "LINEレシート管理",
  "lineReceiptManagement": "LINEレシート管理",
  "points.title": "ポイント管理",
  "points.balance": "ポイント残高",
  "points.totalEarned": "累計獲得",
  "points.totalUsed": "累計利用",
  "points.history": "ポイント履歴",
  "points.earn": "獲得",
  "points.use": "利用",
  "points.expire": "失効",
  "points.refund": "返還",
  "points.adjustment": "調整",
  "points.noTransactions": "取引履歴がありません",
  "receipts.title": "レシート管理",
  "receipts.submit": "レシートを申請",
  "receipts.myReceipts": "申請履歴",
  "receipts.pending": "審査中",
  "receipts.approved": "承認済み",
  "receipts.rejected": "却下",
  "receipts.onHold": "保留",
  "receipts.storeName": "店舗名",
  "receipts.purchaseDate": "購入日",
  "receipts.amount": "金額",
  "receipts.points": "ポイント",
  "receipts.status": "ステータス",
  "receipts.submittedAt": "申請日時",
  "receipts.noReceipts": "レシートがありません",
  "receipts.uploadImage": "レシート画像をアップロード",
  "receipts.submitting": "申請中...",
  "receipts.submitSuccess": "レシートを申請しました",
  "receipts.submitError": "申請に失敗しました",
  "receipts.duplicate": "このレシートは既に登録されています",
  "receipts.expired": "申請期限（7日）を過ぎています",
  "receipts.tooMany": "24時間以内の申請上限に達しています",
  "receipts.fraudWarning": "不正検知",
  "receipts.approve": "承認",
  "receipts.reject": "却下",
  "receipts.hold": "保留",
  "receipts.reviewNote": "レビューメモ",
  "receipts.ocrResult": "OCR解析結果",
  "receipts.calculatedPoints": "算出ポイント",
  "receipts.awardedPoints": "付与ポイント",
  "receipts.statistics": "統計",
  "receipts.pendingCount": "審査待ち",
  "receipts.approvedCount": "承認済み",
  "receipts.rejectedCount": "却下",
  "receipts.totalAmount": "合計金額",
  "receipts.totalPoints": "合計ポイント",
};

// Chinese translations
const zhTranslations: Record<string, string> = {
  // Navigation
  "nav.dashboard": "仪表盘",
  "nav.tasks": "任务列表",
  "nav.reports": "报告",
  "nav.reportStaff": "报告员工",
  "nav.staff": "员工名册",
  "nav.masterControl": "主控制台",
  "nav.reportAnalysis": "AI分析",
  "nav.brands": "品牌管理",
  "nav.businessCards": "名片管理",
  "nav.line": "LINE管理",
  "nav.lineFollowUps": "跟进管理",
  "nav.pendingResponses": "待回复",
  "nav.calendar": "日历",
  "nav.livers": "主播管理",
  "nav.logout": "退出登录",
  
  // Dashboard
  "dashboard.title": "仪表盘",
  "dashboard.inProgress": "进行中",
  "dashboard.completed": "已完成",
  "dashboard.overdue": "已逾期",
  "dashboard.pending": "待处理",
  "dashboard.staffList": "员工列表",
  "dashboard.recentTasks": "最近任务",
  "dashboard.noTasks": "没有任务",
  "dashboard.viewAll": "查看全部",
  "dashboard.createTask": "创建新任务",
  "dashboard.dailyReport": "创建日报",
  
  // Tasks
  "tasks.title": "任务列表",
  "tasks.create": "创建新任务",
  "tasks.search": "搜索",
  "tasks.filter": "筛选",
  "tasks.status": "状态",
  "tasks.staff": "负责人",
  "tasks.deadline": "截止日期",
  "tasks.detail": "详情",
  "tasks.noDeadline": "无截止日期",
  "tasks.all": "全部",
  "tasks.statusPending": "待处理",
  "tasks.statusInProgress": "进行中",
  "tasks.statusCompleted": "已完成",
  "tasks.statusCancelled": "已取消",
  "tasks.clearFilters": "清除筛选",
  "tasks.results": "条结果",
  "tasks.noResults": "没有找到匹配的任务",
  
  // Task Create
  "taskCreate.title": "创建新任务",
  "taskCreate.screenshots": "截图",
  "taskCreate.uploadHint": "最多可上传4张",
  "taskCreate.selectStaff": "选择负责人",
  "taskCreate.deadline": "截止日期（可选）",
  "taskCreate.notes": "备注（可选）",
  "taskCreate.submit": "创建任务",
  "taskCreate.submitting": "创建中...",
  
  // Task Detail
  "taskDetail.title": "任务详情",
  "taskDetail.taskId": "任务ID",
  "taskDetail.status": "状态",
  "taskDetail.staff": "负责人",
  "taskDetail.deadline": "截止日期",
  "taskDetail.createdAt": "创建时间",
  "taskDetail.updatedAt": "更新时间",
  "taskDetail.screenshots": "截图",
  "taskDetail.notes": "备注",
  "taskDetail.sendReminder": "发送提醒邮件",
  "taskDetail.markComplete": "标记完成",
  "taskDetail.reminderHistory": "提醒历史",
  "taskDetail.emailOpened": "已打开",
  "taskDetail.emailNotOpened": "未打开",
  
  // Reports
  "reports.title": "报告",
  "reports.create": "创建新报告",
  "reports.list": "报告列表",
  "reports.staff": "员工",
  "reports.date": "日期",
  "reports.content": "工作内容",
  "reports.issues": "注意事项・问题・原因",
  "reports.remarks": "备注",
  "reports.updatedAt": "更新时间",
  "reports.actions": "操作",
  "reports.noReports": "没有报告",
  "reports.clearFilters": "清除筛选",
  "reports.clearFilter": "清除筛选",
  "reports.results": "条结果",
  "reports.searchResults": "搜索结果",
  "reports.prevMonth": "上月",
  "reports.lastMonth": "上月",
  "reports.thisMonth": "本月",
  "reports.days": "天中",
  "reports.items": "条",
  "reports.country": "国家",
  "reports.all": "全部",
  "reports.allCountries": "所有国家",
  "reports.allStaff": "所有员工",
  "reports.japan": "日本",
  "reports.china": "中国",
  "reports.notLinked": "未关联",
  "reports.noTasks": "无任务",
  "reports.noStaffInCountry": "该国家没有员工",
  "reports.workContent": "工作内容",
  "reports.deleted": "已删除报告",
  "reports.deleteConfirm": "确定要删除这个报告吗？",
  "reports.deleteWarning": "此操作无法撤销。确定要删除吗？",
  "reports.cancel": "取消",
  "reports.delete": "删除",
  "reports.deleting": "删除中...",
  "reports.chatCreate": "通过聊天创建",
  "reports.detail": "报告详情",
  "reports.reportDetail": "日报详情",
  "reports.notFound": "未找到日报",
  "reports.observations": "注意事项・问题・原因",
  "reports.notes": "备注",
  
  // Followups
  "followups.title": "待跟进事项",
  "followups.overdue": "已逾期",
  "followups.pending": "待处理",
  "followups.completed": "已处理",
  "followups.cancelled": "已取消",
  "followups.item": "事项",
  "followups.category": "类别",
  "followups.dueDate": "截止日期",
  "followups.staff": "负责人",
  "followups.reportDate": "日报日期",
  "followups.status": "状态",
  "followups.actions": "操作",
  "followups.markComplete": "标记为已处理",
  "followups.markCancelled": "取消",
  "followups.noFollowups": "没有待跟进的事项",
  "followups.overdueWarning": "超过2天",
  "followups.extractFromReport": "从此日报提取跟进事项",
  "followups.extracting": "提取中...",
  "followups.extracted": "已提取跟进事项",
  "followups.batchExtract": "批量提取",
  "followups.batchExtractDesc": "从过去7天的日报中提取跟进事项",
  "followups.noOverdue": "目前没有待跟进的事项。点击“批量提取”按钮可以从日报中提取跟进事项。",
  "followups.resultTitle": "记录结果",
  "followups.resultCategory": "结果",
  "followups.resultNote": "备注",
  "followups.resultNotePlaceholder": "输入结果详情...",
  "followups.nextActionSuggestion": "AI建议: 下一步行动",
  "followups.willCreate": "创建",
  "followups.skip": "跳过",
  "followups.complete": "完成",
  "followups.suggestingNextAction": "正在建议下一步行动...",
  "followups.nextActionCreated": "已创建下一步行动",
  "followups.viewReport": "查看日报",
  "followups.completedTab": "已完成",
  "followups.allStaff": "全部员工",
  "followups.noCompleted": "没有已完成的跟进事项",
  "followups.note": "备注",
  // Result categories
  "followups.result.closed": "成交",
  "followups.result.closedDesc": "合同/交易已成立",
  "followups.result.continued": "继续",
  "followups.result.continuedDesc": "需要下一步行动",
  "followups.result.pending": "暂停",
  "followups.result.pendingDesc": "暂时搁置处理",
  "followups.result.lost": "失单",
  "followups.result.lostDesc": "合同/交易未成立",
  "followups.result.done": "完成",
  "followups.result.doneDesc": "处理已完成",

  // Report Form
  "reportForm.createTitle": "创建新报告",
  "reportForm.editTitle": "编辑报告",
  "reportForm.staff": "员工",
  "reportForm.selectStaff": "选择员工",
  "reportForm.addNewStaff": "添加新员工",
  "reportForm.newStaffName": "新员工姓名",
  "reportForm.country": "国家",
  "reportForm.date": "日期",
  "reportForm.content": "工作内容",
  "reportForm.contentPlaceholder": "请输入今天的工作内容",
  "reportForm.issues": "注意事项・问题・原因",
  "reportForm.issuesPlaceholder": "请输入注意到的问题",
  "reportForm.remarks": "备注",
  "reportForm.remarksPlaceholder": "请输入其他备注",
  "reportForm.submit": "保存",
  "reportForm.submitting": "保存中...",
  "reportForm.back": "返回",
  
  // Report Staff Management
  "reportStaff.title": "报告员工管理",
  "reportStaff.description": "管理日报员工，设置与员工名册的关联",
  "reportStaff.add": "新增",
  "reportStaff.list": "报告员工列表",
  "reportStaff.name": "姓名",
  "reportStaff.country": "国家",
  "reportStaff.linkedStaff": "关联员工",
  "reportStaff.taskProgress": "任务进度",
  "reportStaff.status": "状态",
  "reportStaff.actions": "操作",
  "reportStaff.notLinked": "未关联",
  "reportStaff.active": "有效",
  "reportStaff.inactive": "无效",
  "reportStaff.noStaff": "没有报告员工",
  "reportStaff.addTitle": "添加报告员工",
  "reportStaff.editTitle": "编辑报告员工",
  "reportStaff.linkTitle": "关联员工",
  "reportStaff.linkDescription": "将与员工名册中的员工关联。关联后可以从日报查看任务进度。",
  "reportStaff.selectLinkedStaff": "选择关联员工",
  "reportStaff.noLink": "不关联",
  "reportStaff.save": "保存",
  "reportStaff.saving": "保存中...",
  "reportStaff.saveLink": "保存关联",
  "reportStaff.cancel": "取消",
  "reportStaff.deleteConfirm": "确定要删除这个报告员工吗？相关的日报也可能被删除。",
  "reportStaff.loading": "加载中...",
  "reportStaff.noTasks": "无任务",
  
  // Staff Management
  "staffMgmt.title": "员工名册",
  "staffMgmt.add": "新增",
  "staffMgmt.name": "姓名",
  "staffMgmt.email": "邮箱",
  "staffMgmt.department": "部门",
  "staffMgmt.country": "国家",
  "staffMgmt.status": "状态",
  "staffMgmt.actions": "操作",
  "staffMgmt.active": "有效",
  "staffMgmt.inactive": "无效",
  "staffMgmt.noStaff": "没有员工",
  "staffMgmt.addTitle": "添加员工",
  "staffMgmt.editTitle": "编辑员工",
  "staffMgmt.save": "保存",
  "staffMgmt.saving": "保存中...",
  "staffMgmt.cancel": "取消",
  "staffMgmt.deleteConfirm": "确定要删除这个员工吗？",
  
  // Login
  "login.title": "登录",
  "login.subtitle": "登录业务自动化系统",
  "login.email": "邮箱",
  "login.password": "密码",
  "login.submit": "登录",
  "login.submitting": "登录中...",
  "login.register": "注册新账号",
  "login.error": "登录失败",
  
  // Register
  "register.title": "注册",
  "register.subtitle": "创建账号",
  "register.name": "姓名",
  "register.email": "邮箱",
  "register.password": "密码",
  "register.confirmPassword": "确认密码",
  "register.submit": "注册",
  "register.submitting": "注册中...",
  "register.login": "已有账号？登录",
  "register.error": "注册失败",
  
  // Common
  "common.loading": "加载中...",
  "common.error": "发生错误",
  "common.save": "保存",
  "common.cancel": "取消",
  "common.delete": "删除",
  "common.edit": "编辑",
  "common.add": "添加",
  "common.search": "搜索",
  "common.filter": "筛选",
  "common.all": "全部",
  "common.yes": "是",
  "common.no": "否",
  "common.confirm": "确认",
  "common.back": "返回",
  "common.next": "下一步",
  "common.previous": "上一步",
  "common.language": "语言",
  
  // Point System
  "nav.points": "积分管理",
  "nav.receipts": "小票管理",
  "nav.lineReceipts": "LINE小票管理",
  "lineReceiptManagement": "LINE小票管理",
  "points.title": "积分管理",
  "points.balance": "积分余额",
  "points.totalEarned": "累计获得",
  "points.totalUsed": "累计使用",
  "points.history": "积分历史",
  "points.earn": "获得",
  "points.use": "使用",
  "points.expire": "失效",
  "points.refund": "退还",
  "points.adjustment": "调整",
  "points.noTransactions": "没有交易记录",
  "receipts.title": "小票管理",
  "receipts.submit": "提交小票",
  "receipts.myReceipts": "申请记录",
  "receipts.pending": "审核中",
  "receipts.approved": "已通过",
  "receipts.rejected": "已拒绝",
  "receipts.onHold": "暂挂",
  "receipts.storeName": "店铺名称",
  "receipts.purchaseDate": "购买日期",
  "receipts.amount": "金额",
  "receipts.points": "积分",
  "receipts.status": "状态",
  "receipts.submittedAt": "提交时间",
  "receipts.noReceipts": "没有小票",
  "receipts.uploadImage": "上传小票图片",
  "receipts.submitting": "提交中...",
  "receipts.submitSuccess": "小票已提交",
  "receipts.submitError": "提交失败",
  "receipts.duplicate": "该小票已经登记",
  "receipts.expired": "已超过申请期限（7天）",
  "receipts.tooMany": "已达到24小时内申请上限",
  "receipts.fraudWarning": "异常检测",
  "receipts.approve": "通过",
  "receipts.reject": "拒绝",
  "receipts.hold": "暂挂",
  "receipts.reviewNote": "审核备注",
  "receipts.ocrResult": "OCR解析结果",
  "receipts.calculatedPoints": "计算积分",
  "receipts.awardedPoints": "实发积分",
  "receipts.statistics": "统计",
  "receipts.pendingCount": "待审核",
  "receipts.approvedCount": "已通过",
  "receipts.rejectedCount": "已拒绝",
  "receipts.totalAmount": "总金额",
  "receipts.totalPoints": "总积分",
};

const translations: Record<Language, Record<string, string>> = {
  ja: jaTranslations,
  zh: zhTranslations,
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ja";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
